### ISSUE TITLE
Ambigious class resolution & --ignore-platform-reqs

### ISSUE THREAD

**Issue by aFluxx** [laravel/cashier-mollie#1]
Hello there,

I'm installing this package on a windows enviroment running homestead and I had to use the `--ignore-platform-reqs` flag.

Do you think this could lead to any complications, or am I free to use this.

Also got the following yellow lines while installing:

```
Warning: Ambiguous class resolution, "Laravel\Cashier\Billable" was found in both "C:/Users/***/Desktop/***/vendor/laravel/cashier/src/Billable.php" and "C:/Users/***/Desktop/***/vendor/laravel/cashier-mollie/src\Billable.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\Cashier" was found in both "C:/Users/***/Desktop/***/vendor/laravel/cashier/src/Cashier.php" and "C:/Users/***/Desktop/***/vendor/laravel/cashier-mollie/src\Cashier.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\CashierServiceProvider" was found in both "C:/Users/***/Desktop/***/vendor/laravel/cashier/src/CashierServiceProvider.php"
and "C:/Users/***/Desktop/***/vendor/laravel/cashier-mollie/src\CashierServiceProvider.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\Http\Controllers\WebhookController" was found in both "C:/Users/***/Desktop/***/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php" and "C:/Users/***/Desktop/***/vendor/laravel/cashier-mollie/src\Http\Controllers\WebhookController.php", the first will be used.
Warning: Ambiguous class resolution, "Laravel\Cashier\Subscription" was found in both "C:/Users/***/Desktop/***/vendor/laravel/cashier/src/Subscription.php" and "C:/Users/***/Desktop/***/vendor/laravel/cashier-mollie/src\Subscription.php", the first will be used.
```

I have the normal cashier package installed and it seems to have some Ambigious class resolutions. As I'm not all to familiar with this I wanted to inform myself if this could lead to complications.
Is it possible to use Laravel Cashier aswell as Laravel Cashier Mollie in one project?

Kind Regards!

**Comment by sandervanhooft** [comment]
Hi,

Congrats on opening the first ticket :).

You can’t run Cashier Mollie next to other Cashier implementations, they are designed to overrule each other.

**Comment by aFluxx** [comment]
Haha, someone has to be first!

Oh ow! I'l look further into it then.

Just wondering then this package is just an extra integration of mollie + cashier? So I can still use all other cashier functionality. Or how should I see this?

I just want to "Bezint, eer I begint" ^^

**Comment by sandervanhooft** [comment]
It’s designed to be a complete Cashier package, like the one for Stripe and Braintree, but for Mollie.

**Comment by aFluxx** [comment]
Okay thanks! I'll swap it out and play around with it! I'll let you know my findings!
