### ISSUE TITLE
Quantity instantly creates payments

### ISSUE THREAD

**Issue by MSnoeren** [laravel/cashier-mollie#10]
I'm currently creating software that uses the quantity system. A user can create as many as they like and pay for each one of them monthly. Currently, a product is around 50 cents. When the customer adds 10 products, 10 payments will be created and I'll pay 10 times the transaction costs, which is around half the price of a product using SEPA.

Is there any way to queue these payments and send them in one big chunk daily (or any other interval), perhaps during the refresh of a subscription? I guess the software should keep track of the usage this way to calculate the time used of products.

A solution could be to let customers buy products in steps of 10 and chunk payments this way, although I prefer the precise quantity.

Thoughts?

**Comment by sandervanhooft** [comment]
Hi @MSnoeren ,

Have you checked in the Mollie dashboard that 10 payments were created? They should be all combined into a single OrderItem, not 10.

If it's 10 OrderItems, this would only occur on the first payment, on subsequent payments the scheduler will combine it into a single Order and payment. (Would still not be ok obviously!)

**Comment by MSnoeren** [comment]
Currently I'm triggering the `updateQuantity` function **each** time a customer adds or removes a product. This means it'll create a payment for every quantity change. Using `updateQuantity` makes sure the quantity is always the same as the amount of active products. The payment is instantly processed and sent to Mollie; my testing-dashboard confirms this. The user has a valid mandate.

The behavior code can be found at; https://github.com/laravel/cashier-mollie/blob/61a3f0b40776fc2a395868be866e7f9281c3b38a/src/Subscription.php#L660

The `updateQuantity` function requests the `restartCycleWithModifications` function which then requests the order to be processed.

**Comment by sandervanhooft** [comment]
Perhaps we could add a default flag `processNow = true`?

**Comment by sandervanhooft** [comment]
Alternatively you could place a layer in between (Front-end JS?) to delay the update to the back-end, capturing all 10 updates in a single request.

**Comment by MSnoeren** [comment]
The `$processNow = true` flag looks like a great idea. This way we can run the Cashier command, for example, daily and group payments per billable model, cutting costs. It will also support the anchor date feature which is is not yet implemented, but a fallback would be to run the Cashier command.

**Comment by sandervanhooft** [comment]
What do you think, should `processNow` default to `true` or `false`?

Given your use case, I'm leaning towards `false`.

**Comment by MSnoeren** [comment]
I think it should be `true`, as the current behavior is also `true`. I'm switching a lot of quantities with small costs, so it's useful to me to cut the costs and push the payment into one large one, but I can imagine that other applications want to bill their customers immediately whenever they add, for example, another user at a higher cost.

**Comment by sandervanhooft** [comment]
Ok, we'll take that route for now.

**Comment by sandervanhooft** [comment]
For clarity the flag will be named `invoiceNow`.

`processNow` set to `false` suggests that the quantity is not instantly updated. Which it is, it's only invoiced later.

**Comment by sandervanhooft** [comment]
I've prepared a solution for the v1 release, planned for end of the month. 🤞
