### ISSUE TITLE
When is FirstPaymentPaid dispatched?

### ISSUE THREAD

**Issue by sigmoidal** [laravel/cashier-mollie#103]
Hi,

I wrote an event handler (listener) and registered a custom EventServiceProvider in my package to intercept and handle the FirstPaymentPaid. 

Then (in test mode), the user selects the desired plan and he is redirected to the Mollie payment screen, where he can select a status for the payment. The webhook I have specified for the first time payment is triggered correctly (unless of course "Open" is selected) and the respective Controller method is called.

Via the mollie api I can read the payments for the user and the statuses are appropriately set in the mollie system.

Although, my listeners are registered to intercept the FirstPaymentPaid event, I don't see it being dispatched. I even tried to listen for "*", but there does not seem to be any references to FirstPaymentPaid.

Could someone possibly explain when is the FirstPaymentPaid event dispatched and how it is supposed to be used ?

**Comment by sandervanhooft** [comment]
Hi @sigmoidal ,

The FirstPaymentPaid event is dispatched when the webhook called is AND the payment is known in the system (table `orders`) AND the payment is paid: see the [FirstPaymentWebhookController](https://github.com/laravel/cashier-mollie/blob/dff0ab91a5c2020fccea0b39d01eb13eece7c221/src/Http/Controllers/FirstPaymentWebhookController.php#L27).

Just to be sure: can you double check that your listener is working by dispatching your own event and listening for it?

**Comment by sigmoidal** [comment]
Hi @sandervanhooft,

Thank you for the swift response.

Ok, my orders table is empty, it doesn't seem anything is added there. I guess I am missing something (first time cashier user...)

I have manually dispatched a FirstPaymentPaid, it gets intercepted and handled without any problems.

Am I supposed to configure/register something for the Orders to be updated ?

thank you.

**Comment by sandervanhooft** [comment]
Hi @sigmoidal ,

I made a mistake in my previous comment, see my edits. The order (and payment id) are **not** persisted in the system before the first payment has been successfully processed. This is by design.

**Comment by sandervanhooft** [comment]
I am closing this issue for now. Let me know if it should be reopened.

**Comment by sigmoidal** [comment]
Well, thanks for trying to help. Unfortunately there seems to be a problem with first payments.
No matter what I try, the mandate is not written in the database even if when the first payment is completed and appears to be fine.

If I query the mandates directly through the mollie API for the user, a mandate is there. 
Am I supposed to manually use the first payment handler and store the mandate it in the db myself, or this package is supposed to do that?

Do note that I now do receive the mandate in the array sent over by mollie through the webhook.

**Comment by sandervanhooft** [comment]
@sigmoidal Can you try making `mollie_mandate_id` fillable on your billable model?

**Comment by sigmoidal** [comment]
It is set as fillable, same behavior, mollie_mandate_id is null even after I set the first payment as PAID.

I noticed the user's mollie_mandate_id is set in FirstPayment::execute() using the payment's mandateId, but this function is never triggered. Do I have to call it manually? What triggers it and when?

Any help is greatly appreciated.

**Comment by sandervanhooft** [comment]
[It's triggered when Mollie calls the webhook.](https://github.com/laravel/cashier-mollie/blob/62aa89f4f27fd78fbb255ebbf12a597b31812627/src/Http/Controllers/FirstPaymentWebhookController.php#L19:L34)

**Comment by sigmoidal** [comment]
Ok, this was a mistake from me. The problem was that I had reimplemented the Subscription and thus the logic was messed up. Switching back to the original implementation of Subscription works as expected.

thanks for your help.

**Comment by JessedeB** [comment]
> [It's triggered when Mollie calls the webhook.](https://github.com/laravel/cashier-mollie/blob/62aa89f4f27fd78fbb255ebbf12a597b31812627/src/Http/Controllers/FirstPaymentWebhookController.php#L19:L34)

Still not being triggered, it seems like the event isn't even dispatched 🤔 Logged the dispatch and event listener but nothing is set into the log file. Mollie is successfully returning the correct webhook, the CSRF token is excluded from the webhook too.

```php
use Illuminate\Support\Facades\Log;
use Laravel\Cashier\Events\FirstPaymentPaid;

class FirstOrderPaymentPaidListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle(FirstPaymentPaid $event)
    {
        Log::info('First payment status ' . $event);
    }
}
```
```php
protected $listen = [
        FirstPaymentPaid::class => [
            FirstOrderPaymentPaidListener::class,
        ],
];
```

**Comment by sandervanhooft** [comment]
If you lookup the payment in Mollie's dashboard, what is it saying about the webhook calls being made?

On desktop, you can see a list of events in a column on the right.
