### ISSUE TITLE
Multi-currency

### ISSUE THREAD

**Issue by Jamesking56** [laravel/cashier-mollie#104]
Does this package support taking payments in multiple currencies? If so, how do I configure per Billable entity what their chosen currency is?

**Comment by sandervanhooft** [comment]
Hi @Jamesking56 ,

It does support multiple currencies, but the currency is defined on the plan, not on the billable entity. You could define a plan for each currency you'd like to support (i.e. `gold_monthly_eur`).

**Comment by Jamesking56** [comment]
Thanks for the fast response,

Is there a way I can generate the plans array rather than hard-code it?

What happens when a plan is removed from the array that has active
subscriptions?

Cheers.

**Comment by sandervanhooft** [comment]
> What happens when a plan is removed from the array that has active
subscriptions?

It should be left in for users that are still on the plan. I recommend providing a subset of these plans as active plans to new customers.

> Is there a way I can generate the plans array rather than hard-code it?
You can override the PlanRepository. There are some discussions on how to this in this repo. (i.e. #87)

**Comment by Jamesking56** [comment]
Thanks @sandervanhooft :+1:
