### ISSUE TITLE
WebhookController throws exception when payment failed because of missing mandate.

### ISSUE THREAD

**Issue by edcoreweb** [laravel/cashier-mollie#105]
In case of a failed payment which doesn't have a mandate (user deleted card or something), the controller fails, which causes the webhook to fail, and the subscription is not canceled.

https://github.com/laravel/cashier-mollie/blob/develop/src/Http/Controllers/WebhookController.php#L30

https://github.com/laravel/cashier-mollie/blob/develop/src/Order/Order.php#L356

This line throws an exception which is not caught.

https://github.com/laravel/cashier-mollie/blob/develop/src/Billable.php#L390

Proposed fix is to add some error handling in the `mollieMandate` method.

```php
/**
 * @return \Mollie\Api\Resources\Mandate|null
 */
public function mollieMandate()
{
    $id = $this->mollieMandateId();
    $mandate = null;

    if (! empty($id)) {
        try {
            $mandate = $this->asMollieCustomer()->getMandate($id);
        } catch (ApiException $e) {} // A revoked mandate may no longer exist, so throws an exception
    }

    return $mandate;
}
```

Can put together a pr if needed.

**Comment by sandervanhooft** [comment]
Hi @edcoreweb,

Good catch. I happen to be working on the mandate checks right now, so I'll include a fix there.

It will be a bit more specific, only catching status `404` or `410`. And `try` will exclude the `asMollieCustomer` part.

**Comment by edcoreweb** [comment]
@sandervanhooft Great!

**Comment by sandervanhooft** [comment]
Hi @edcoreweb ,

Just checked with Mollie's support because I was unsure about the API behaviour. A revoked mandate will remain retrievable, but will have a status `invalid`. So I don't think this would break this code actually. Can you figure out what triggered your error?

**Comment by sandervanhooft** [comment]
Nonetheless, I've included a fix in `develop`

**Comment by edcoreweb** [comment]
@sandervanhooft Sorry for the late reply, not sure why this happened but it can happen.
Maybe Mollie needs to investigate this.

The user payments:
![Screenshot_4](https://user-images.githubusercontent.com/9083523/68469788-85325280-0223-11ea-8df7-d06fea45c973.png)

The missing mandate:
![Screenshot_5](https://user-images.githubusercontent.com/9083523/68469809-94b19b80-0223-11ea-97a5-356217296853.png)

This was retrieved with Postman using Mollie's api. Some sensitive data has been removed.

As you can see the first payment worked fine, has the mandate. Second payment a month later, with same mandate failed because of it missing.

Maybe this helps someone, but happy to hear it's handled nonetheless.

**Comment by sandervanhooft** [comment]
Big thanks for reporting this back in full detail. I'll notify Mollie support.

**Comment by sandervanhooft** [comment]
Cleared it up: exception 404 is the proper response for fetching a revoked mandate.
