### ISSUE TITLE
Make some models macroable

### ISSUE THREAD

**Issue by larsjanssen6** [laravel/cashier-mollie#107]
Hi,

Would it be an idea to make some models `macroable`. 

For example I need to add an `address` to the `order` model. If the `order`
model was `macroable` I could add the relation like this:

**Boot method in serviceprovider:**

```
Illuminate\Database\Eloquent\Builder::macro(‘address’, function() {
    $model = $this->getModel();
    
    if($model instanceof App\Address) {
         return $model->belongsToMany(App\Address::class);
    }
    unset(static::$macros['address']);
    return $model->address();
 });
```

Would you accept a PR for this or is there a better way?

Thanks!

**Comment by sandervanhooft** [comment]
Hi @larsjanssen6 ,

I'm ok with making things macroable. Another way would be to make classes swappable by setting the class in the config, but that would take a lot of work.

**Comment by larsjanssen6** [comment]
Looks like this is not possible on models yet in Laravel:

https://github.com/laravel/ideas/issues/1870

**Comment by larsjanssen6** [comment]
For now I have overwritten the `subscription` class but maybe in the future we could add this `macroable` trait if it's supported would be nice :)

**Comment by sandervanhooft** [comment]
Yeah that was what I was afraid of with the macroable trait...

Just curious, how did you overwrite it?

**Comment by larsjanssen6** [comment]
@sandervanhooft I made a custom class and extend the `Subscription mollie` class (only need this for Laravel nova).

**Comment by sandervanhooft** [comment]
Good to know. Thanks!

**Comment by javoscript** [comment]
I recently made a little package which allows to add macros to Eloquent models:

https://github.com/javoscript/laravel-macroable-models

Let me know if you try it out and if it is of any use! =)
