### ISSUE TITLE
First payment is not affected by tax rule.

### ISSUE THREAD

**Issue by MSnoeren** [laravel/cashier-mollie#11]
The first payment is not affected by tax and I can't seem to find out why. The first payment is 50 cents exactly (as configured) and all payments after (configured as 41 cents with 21% tax) are sometimes 50 cents but sometimes 49 cents as well.

**Comment by sandervanhooft** [comment]
Is this a first payment in trial mode?

**Comment by MSnoeren** [comment]
No, it's not. It also appeared to me once. All payments from now on are correct, including the first one. It could've been my configuration. For now it can be closed until it occurs again or someone else experiences the same.

**Comment by sandervanhooft** [comment]
Thanks for the follow-up! Rounding can be a hard-to-tackle issue, so please let me know if you come across other instances.
