### ISSUE TITLE
SubscriptionResumed Event

### ISSUE THREAD

**Issue by pascallieverse** [laravel/cashier-mollie#114]
It would be nice to have a event for when a subscription is resumed again. If you agree @sandervanhooft I could make a pull request for adding the event.

**Comment by sandervanhooft** [comment]
Hi @pascallieverse,

Not convinced yet... I don't see a real benefit here as you can easily wrap the method call (i.e. in a Controller) and add an event there if you need it. The method itself runs synchronously.

What do you think?

**Comment by pascallieverse** [comment]
Indeed, just had a look at the source.

It wouldn't fit because there is also no notification on when a user cancel the subscription, only when its on the end of the period and its cancellend. It could save some redundancy to implement a notification at the listeners..

**Comment by sandervanhooft** [comment]
I agree with your consistency argument. I welcome a PR for this!

**Comment by sandervanhooft** [comment]
(Don't forget to update the docs :) )

**Comment by sandervanhooft** [comment]
I may be able to include it in tomorrow's release. Otherwise it will be sometime next week.
