### ISSUE TITLE
Question about billing cycle

### ISSUE THREAD

**Issue by jamie2323** [laravel/cashier-mollie#118]
Hi, 

Great package love it!

Quick question, I would like to bill a fixed amount every x of the month. The amount is
**always** the same even if the user has subscribed for example 10 days ago. 

I already saw I can change the `nextPaymentAt` but how do I modify the `cycle_started_at` to be in the future?

Right now I have this:

```
 $subscription = $user
                ->newSubscription($name, $fields->plan)
                ->nextPaymentAt(Subscription::nextPaymentDate())
                ->quantity($fields->quantity)
                ->create();
```

Is it possible with this package?

Thanks for your work!

**Comment by sandervanhooft** [comment]
Thanks @jamie2323 !

What you're looking for is called "anchoring the billing cycle".

It's not supported yet, see #66.

I'll be keeping that ticket as a reference and close this for now. Let me know if it should be reopened.
