### ISSUE TITLE
⚡ Spark Mollie is coming

### ISSUE THREAD

**Issue by sandervanhooft** [laravel/cashier-mollie#119]
Hi everyone!

Thanks for all of your enthusiasm for this Cashier package.

As announced at Laracon.EU Amsterdam, I'm working on a Laravel Spark integration for Mollie as well. It will be a first class, official part of Laravel Spark.

Getting Spark to work with Mollie was not as simple as replacing the Stripe Cashier package with Mollie's. I wish it was that simple. I had to make changes to Spark itself as well. I went over the whole codebase with a microscopic comb.

Before we're going public with Spark I'm opening up an Alpha version to a select group of artisans.

If you're interested or want to get a head start on your Spark-Mollie project, you can ~register here~. (Edit: registration closed)

There will be a dedicated Slack channel to have a chat and answer any questions.

Here's the link again: [register](https://docs.google.com/forms/d/e/1FAIpQLSd3YET2i72XLdCT334mWX1F6q33Fn4X_57sUgxtoeltGjoN_A/viewform?usp=sf_link).

Looking forward to see you there,

Sander

**Comment by sandervanhooft** [comment]
Quick update: we're aiming for a public release in April.

**Comment by yamenarahman** [comment]
@sandervanhooft Great work man! I know this question is somehow out of scope, but are there any plans to also support Paddle? I'm willing to contribute to a Cashier-Paddle package.

**Comment by sandervanhooft** [comment]
Thanks @yamenarahman ! I know Marcel Pociot has been talking about Cashier Paddle support. For me, it's out of scope.

And in full disclosure, I'm also getting paid by Mollie to build and maintain these Laravel integrations, so I'm not in a position to push Paddle here 😄.

**Comment by spooksie** [comment]
Awesome, cannot wait :)

**Comment by alexander-rieder** [comment]
So when will it be there? I'm currently at the start of a new project and are interested in Laravel Spark Using Mollie (... and SEPA direct debit ;) )

**Comment by sandervanhooft** [comment]
Hi everyone,

I've been in touch with @taylorotwell and he has a lot on his plate right now.

We are looking into the best way to provide you with a) Spark Mollie and b) durable support.

Meanwhile you can get access to the alpha (99% done) and start developing. This is how:

1. Ensure you have a valid license for the latest Spark (Aurelius) edition.
2. Star [laravel/spark-aurelius](https://github.com/laravel/spark-aurelius) in Github. If you don't have access, you can invite yourself to this repository via the [spark.laravel.com](https://spark.laravel.com) dashboard.
3. Ask for an invite by leaving a reply below 👇.

**Comment by mannieg** [comment]
@sandervanhooft can I get an invite please just starred the repo 😄

Thanks for the great work!

**Comment by fetds** [comment]
Spark Mollie support only hosted payment pages?

What about Mollie Components?

**Comment by sandervanhooft** [comment]
@fetds Mollie components are great but only support creditcard payments. That’s why Spark Mollie only supports the hosted checkout pages. Which works great.

**Comment by Reached** [comment]
I would like an invite, very excited for this :)!

**Comment by spooksie** [comment]
Invite please :) I'm ready to test this out

**Comment by jackwakefield** [comment]
If I could get an invite that'd be great, thanks in advance!

**Comment by sandervanhooft** [comment]
Hi @jackwakefield ,

I've closed beta invites, as we're near the launch - this Thursday! 🎉

**Comment by RyonMB** [comment]
So how can I use it 🎉. Is it released and where can I check it. Very excited to use it!

**Comment by sandervanhooft** [comment]
Hi @RyonMB ,

Thanks for the ❤️!

I’ll be releasing a blog post on this today. But essentially you go to spark.laravel.com. 

1. Make sure to have a recent Spark license. With this license you can now choose between Stripe and Mollie edition of Spark
2. Get Spark Mollie repository access at spark.laravel.com/settings#github
3. Follow the installation instructions in the Spark Mollie repository.

**Comment by sandervanhooft** [comment]
[Here's the blog post](https://www.sandervanhooft.com/blog/laravel/now-available-laravel-spark-for-mollie/)
