### ISSUE TITLE
Invoice filenames are month-based.

### ISSUE THREAD

**Issue by MSnoeren** [laravel/cashier-mollie#12]
When downloading an invoice using `$order->invoice()->download()`, the filename is automatically generated. This filename assumes that an invoice will be created monthly, as its format is "`month`_`year`.pdf".

The line for this behavior is located at: https://github.com/laravel/cashier-mollie/blob/61a3f0b40776fc2a395868be866e7f9281c3b38a/src/Order/Invoice.php#L473

I guess using the automatically generated ID as default filename, as found in the invoice itself, is better. However, allowing the name to be overridden is also a great addition. Thoughts?

**Comment by sandervanhooft** [comment]
I agree @MSnoeren that the automatically generated invoice reference (id) would be a better default.

Perhaps we could bind an `InvoiceFilenameGenerator` into the container with this behaviour?

It could take the Invoice object as input.

**Comment by MSnoeren** [comment]
Yeah, that would be great. If neccesary, others can create a custom class to generate their own filenames.

**Comment by sandervanhooft** [comment]
Oh sorry
 

I meant `orderId_app_name_snake_case.pdf`

**Comment by MSnoeren** [comment]
Yeah, looks great. Filenames will be unique and traceable.

**Comment by sandervanhooft** [comment]
Putting it on my list. Feel free to submit a PR, otherwise I'll pick it up whenever I find the time.

**Comment by Mindexperiment** [comment]
Hi guys,
I'm going to use mollie with cashier package and can help on enhancements if needed.

Here in italy we organize phisical invoice archives  by a number (called protocol, similar to invoice number) but when we needs to manage digital invoices a common patters is:

yyyymmdd_invnumber.pdf

Is unclear what app_name is for? if you refer to config('app.name') this can be userd by company with more than one department or for invoices downloaded by customer then you can simply:

yyyymmdd_invnumber_appname.pdf

**Comment by sandervanhooft** [comment]
Thanks @mindexperiment,

The app name indeed refers to the config app name. Invoices tend to end up in a customer’s download folder, appending the app name will make it more readable there.

**Comment by sandervanhooft** [comment]
I have prepared this for the v1 release. The separate filename generator is not yet included. Feel free to send in a PR for that.
