### ISSUE TITLE
Lumen support?

### ISSUE THREAD

**Issue by marcelmerkx** [laravel/cashier-mollie#120]
Hi there - question: 

will cashier-mollie support Lumen? 

thanks!!

**Comment by sandervanhooft** [comment]
I haven't tested cashier-mollie against Lumen. But I don't see any reason why it wouldn't be compatible.

**Comment by marcelmerkx** [comment]
dankjewel Sander, we will make a clean Lumen project and give it a try. It did not play nice with our lumen project.
mvrgr

**Comment by marcelmerkx** [comment]
Sander, 

clean lumen 6.0, then running a "php artisan cashier:install" , does not work rightaway.

After resolving some more initial errors, we get 'stuck' on 
<Call to undefined method Laravel\Lumen\Routing\Router::namespace()>
from webhooks.php. As namespace() is not supported in Lumen, we would need to edit vendor code. Sure that can be fixed but then a next issue arises....

I am guessing you won't be in a position to fix this soon, or would you?  (so we can consider what to do next ourselves....)

thanks!
Marcel

**Comment by sandervanhooft** [comment]
Lumen support is not on the roadmap.

**Comment by marcelmerkx** [comment]
gottit. thanks
