### ISSUE TITLE
Can't integrate with Laravel 5.8 - No API key provided

### ISSUE THREAD

**Issue by paligiannis** [laravel/cashier-mollie#125]
I am already a customer in Mollie and Mollie API is working fine with my application in production.
I installed Mollie cashier for subscription plans.

I have this piece of code.
`$user = \App\User::find(9);
        $result = $user->newSubscription('main', 'example-1')->create();
        dd($result);`

I have followed all the steps for installation:
Packages: 
- "laravel/framework": "5.8.*",
- "laravel/cashier": "^10.5"
- "laravel/cashier-mollie": "1.8.0"

The error I get, even if the configuration I have in cashier.php is correct I the following:
**No API key provided. (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.**
https://prnt.sc/q8gb5m

I have also clear the cache, config files and views.

Anyone having the same issue?

**Comment by RobertBoes** [comment]
laravel-cashier-mollie is a replacement for laravel/cashier. The error is caused by cashier, which is built with Stripe. You should remove the laravel/cashier requirement and then the error should be gone :)

**Comment by paligiannis** [comment]
> laravel/cashier-mollie is a replacement for laravel/cashier. The error is caused by cashier, which is built with Stripe. You should remove the laravel/cashier requirement and then the error should be gone :)

Thank you very much. Now error 422 but I'l inspect it on my own. Thanks a lot :)
