### ISSUE TITLE
Prevent duplicate Orders when processing FirstPayment

### ISSUE THREAD

**Issue by sandervanhooft** [laravel/cashier-mollie#126]
When for whatever reason the webhook for the first payment is called multiple times, each time a new Order will be created and all actions will be executed.

**Comment by hendrikhaack** [comment]
Is there currently any (temporary) fix for this issue?

**Comment by sandervanhooft** [comment]
This has been fixed on the latest release. Can you check it out?

Here's the PR: #310 .

**Comment by hendrikhaack** [comment]
Sorry, you're totally right! I only found this open issue from yourself and didn't check the latest release.
