### ISSUE TITLE
How to use setApiKey()

### ISSUE THREAD

**Issue by cvgeldern** [laravel/cashier-mollie#129]
In my application I use multiple Mollie accounts for multiple purposes. With the bare mollie-api-php package I've the opportunity to set the api key dynamically with
`$mollie->setApiKey("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM");`
See the mollie-api-php readme.

Currently my code is as provided by the cashier-mollie readme

        if (!$user->subscribed($name, $plan)) {

            $result = $user->newSubscriptionViaMollieCheckout($name, $plan)->create();

            if(is_a($result, RedirectToCheckoutResponse::class)) {
                //return $result; // Redirect to Mollie checkout
                return $result->payment()->getCheckoutUrl();
            }

            //return back()->with('status', 'Welcome to the ' . $plan . ' plan');
         }

        return back()->with('status', 'You are already on the ' . $plan . ' plan');

Where and how to set the Mollie api key?

**Comment by sandervanhooft** [comment]
Cashier Mollie (especially the scheduler) does not support this.

**Comment by sandervanhooft** [comment]
But if you really need it for some very special case, you could call it as `mollie->setApiKey(...);`.

⚠️ It is strongly advised to only use this if you know what you are doing and are fully aware of the effects on Cashier.

**Comment by cvgeldern** [comment]
> 
> But if you really need it for some very special case, you could call it as `mollie->setApiKey(...);`.
I tried that, I get the error the method doesn't exist.

> 
> ⚠️ It is strongly advised to only use this if you know what you are doing and are fully aware of the effects on Cashier.
Some effects are already taken care of. But I'm still looking into the most challenging one, letting Cashier set the api key on every recurring payment. The models are in place, but I'm scanning through the code to see where to customize the appropriate classes. 

Thanks for your reply. If I find/create a solid solution, I'll share.
