### ISSUE TITLE
Question regarding subscription without Mandate Up Front

### ISSUE THREAD

**Issue by EvgeniyHablak** [laravel/cashier-mollie#132]
So our main idea is to give some certain users a subscription plan for customizable period of time for free (not to oblige them to specify the credit card details). 

The first idea was to create a subscription record in `subscriptions` table to with custom `trial_ends_at` and chosen plan. The question is won't it break something (e.g. cashier:run command)?

Thanks in advance!

**Comment by sandervanhooft** [comment]
Cashier Mollie support this using _generic trials_.
