### ISSUE TITLE
Subscription not created after successful payment

### ISSUE THREAD

**Issue by justkidding96** [laravel/cashier-mollie#136]
Hi,

After I redirected to the checkout of Mollie in test mode. I selected that the payment was successfully, but the subscription or order are not created. What I'm doing wrong?

**Comment by sandervanhooft** [comment]
Hi @justkidding96 ,

Can you check in the Mollie dashboard that your webhookUrl can be reached? You can find this on the payment details, in the right pane.

If the webhook cannot be reached, consider using `valet share` or `ngrok` and configure your app url in `.env` accordingly.

**Comment by justkidding96** [comment]
Hi @sandervanhooft 

I'm working on local environment but also tested on public domain. Both are not working. Also is the webhook call not only a update. Does Cashier something with the webhook?

**Comment by sandervanhooft** [comment]
> Both are not working.

Can you elaborate? What does the Mollie dashboard show about the webhook calls?

**Comment by justkidding96** [comment]
Hi @sandervanhooft 

Inside the Mollie dashboad I get the message that the webhook has returned a 500 error. This is correct because the webhook url is on non public domain. But the problem is that the application doesn't create a subscription or order before I redirect the user to the payment screen.

For what I known is that the webhook is just to check if the payment is paid or not. Does Cashier needs the webhook data?

**Comment by sandervanhooft** [comment]
Ah that clears it up. This is correct behaviour. Cashier uses the webhook call to retrieve the payment and execute the actions in its metadata. As you can see in the dashboard, the metadata includes the action to create the subscription.

**Comment by sandervanhooft** [comment]
Just reread this thread: error 500 signals an error somewhere in your app. Can you check your logs?

**Comment by sandervanhooft** [comment]
Your webhook being unreachable would result in a 404 in Mollie’s dashboard.

**Comment by justkidding96** [comment]
@sandervanhooft I resolved the issue already. After you said that Cashier depends on the webhook I faked the Mollie webhook request with Postman and everything was working.

But I think that the documentation needs some clarification about this. It was not clear for me how the system is working. After some digging in the package I just found out how...

**Comment by sandervanhooft** [comment]
Thanks for following up. No problem, enjoy!

**Comment by mahesh9696** [comment]
@sandervanhooft I have set webhook URL and subscription can create successfully in DB but not in Mollie Why ?
