### ISSUE TITLE
is Multicurrency enabled ?

### ISSUE THREAD

**Issue by mazraara** [laravel/cashier-mollie#138]
I am trying to use USD as a payment currency, however i am getting the following error.

No suitable payment methods found. Documentation: https://docs.mollie.com/guides/handling-errors

By default this package is supporting only EUR or Multicurrency ?

when set to use EUR, it throws 

All actions must be in the same currency {"userId":1,"exception":"[object] (Laravel\\Cashier\\Exceptions\\CurrencyMismatchException(code: 404): All actions must be in the same currency at /var/www/project/laravel/vendor/laravel/cashier-mollie/src/FirstPayment/Actions/ActionCollection.php:24)

**Comment by sandervanhooft** [comment]
It supports multicurrency, but accepting USD also requires these methods to be enabled on your account.

**Comment by sandervanhooft** [comment]
This seems to be two separate issues.

1. The Mollie exception. See my previous comment

2. What are you trying to do? Do you have some code to share?

**Comment by sandervanhooft** [comment]
Closed due to inactivity

**Comment by Paulsky** [comment]
Hello @sandervanhooft , I'm receiving this error as well if I use USD in combination with coupons. All my coupons and plans are in USD. But when I debug the error on line 23 in ActionCollection, the ApplySubscriptionCouponToPayment getTotal() always returns 'EUR'. Did I mis a config setting somewhere?

**Comment by Paulsky** [comment]
FYI: I created a temporally fix with the following (I think I'm missing a config setting somewhere?):

`Cashier::useCurrency(env('MOLLIE_CURRENCY', 'USD'));` 

Inside the boot() function in my AppServiceProvider.

**Comment by rubenbuijs** [comment]
Thanks @Paulsky, this solved the issue that I had with applying coupons.
