### ISSUE TITLE
Class 'NumberFormatter' not found 

### ISSUE THREAD

**Issue by mazraara** [laravel/cashier-mollie#142]
Getting the following error
Class 'NumberFormatter' not found (View: /var/www/api.fusebox.local.dolphiq.eu/laravel/resources/views/vendor/cashier/receipt.blade.php)

Trying to download an invoice by calling return auth()->user()->downloadInvoice($orderId)

package using ->             

"name": "laravel/cashier-mollie",
 "version": "v1.10.2",

**Comment by sandervanhooft** [comment]
It means the php intl extension is missing.

https://stackoverflow.com/questions/30554177/fatal-error-class-numberformatter-not-found
