### ISSUE TITLE
Other model then User

### ISSUE THREAD

**Issue by Paulsky** [laravel/cashier-mollie#143]
Hello,

Is it possible to use another model then the User model? Something like this Cashier issue; https://github.com/laravel/cashier/issues/545

In that issue an example scenario is described like this;  A User can have multiple shops. These shops have different paid plans (no free plan). Like Bronze, Sliver, and Gold subscriptions.

So the User itself doesn't have subscriptions, but the shops he owns do have subscriptions.

Can this scenario be achieved by this package?

**Comment by sandervanhooft** [comment]
Yes,simply add the billable trait to the Shop model.

**Comment by Paulsky** [comment]
Thank you🙏
