### ISSUE TITLE
Order table name

### ISSUE THREAD

**Issue by Paulsky** [laravel/cashier-mollie#145]
Hello,

I already have an existing orders table. I would like to rename the Mollie Order tables to:
- mollie_orders
- mollie_order_items

But, can I set the table names for the corresponding models...? 

Thank you in advance

**Comment by sandervanhooft** [comment]
Hi @Paulsky ,

No, sorry, it’s not possible. Good idea though, I’ll put overriding the models on the roadmap. Would be a v2 feature, so will not solve your problem right now. Sorry for that.

**Comment by Paulsky** [comment]
Thank you in advance @sandervanhooft ! I had to take a good look at my own table naming convention and I decided I can rename my own table. So that's a workaround for now.
