### ISSUE TITLE
Multiple transactions displayed for single payment

### ISSUE THREAD

**Issue by mazraara** [laravel/cashier-mollie#150]
I am using the below lines of code to make the first payment 

        $result = $user->newSubscription('main', 'pro-yearly')->create();
        //If new user without mollie mandate then redirect to mollie
        if (is_a($result, RedirectToCheckoutResponse::class)) {
            $redirect = $result->payment()->getCheckoutUrl();
        }

In the order table and oder items tables i am having having multiple records. check below screenshot.

![image](https://user-images.githubusercontent.com/2024844/74037516-7145ea80-49e4-11ea-9877-059c8e599216.png)

![image](https://user-images.githubusercontent.com/2024844/74037544-7c991600-49e4-11ea-9625-e95303170297.png)

**Comment by mazraara** [comment]
i am trying to get the invoices by calling auth()->user()->orders->invoices() it returns empty, but auth()->user()->orders works and returns multiple records

**Comment by sandervanhooft** [comment]
#126

**Comment by sandervanhooft** [comment]
> i am trying to get the invoices by calling auth()->user()->orders->invoices() it returns empty, but auth()->user()->orders works and returns multiple records

This is another issue. Can you open a separate ticket?

**Comment by mazraara** [comment]
Sure, thanks!
