### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Paulsky** [laravel/cashier-mollie#152]
Could you please advice what's the best way to test this package? I would like to test for example swapping Subscriptions and redeeming Coupons. But therefore the owner should be already on a subscription. 

Do you have an example to subscribe the owner to a new subscription with bypassing the Mollie checkout flow?

Thank you in advance!

**Comment by sandervanhooft** [comment]
The tests folder includes a whole set which you can use as examples, a lot of these are integration tests. So tested against Mollie’s API. Easiest way is to obtain and store a mandate id and customer id on the billable model. This way the subscriptions etc will be generated without the need to go through checkout.

**Comment by Paulsky** [comment]
Alright! Thank you very much! 🙏
