### ISSUE TITLE
How does automatic renewal work exactly?

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#153]
Dear Developers,

As I've looked through the code, and understand it correctly, it seems to me that the renewal time (_order_items_ -> _process_at_) is exactly the same as the expiration time (_subscriptions_ -> _cycle_ends_at_) of a subscription. Is this true?

And does this mean that I would need to run cashier:run every minute? And even if I would, would there be some time in between the expiration and the renewal time where the user is not able to user their subscription features?

Thank you for your time!

Sincerely,

zqstack

**Comment by sandervanhooft** [comment]
1. True
2. No
3. No. The subscription is optimistic: the user is subscribed until cancelled/payment failed.
