### ISSUE TITLE
Call to a member function orderItemPreprocessors() on null

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#154]
Dear Developers,

As I scheduled `cashier:run` I am finding these errors in my laravel.log file. Do you know why this is happening?

`[2020-02-19 10:05:02] local.ERROR: Call to a member function orderItemPreprocessors() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function orderItemPreprocessors()$`
`[stacktrace]`
`#0 /www.mysite.com/vendor/laravel/cashier-mollie/src/Order/OrderItem.php(180): Laravel\\Cashier\\Subscription::preprocessOrderItem()`
`#1 /www.mysite.com/vendor/laravel/cashier-mollie/src/Order/OrderItemCollection.php(118): Laravel\\Cashier\\Order\\OrderItem->preprocess()`
`#2 [internal function]: Laravel\\Cashier\\Order\\OrderItemCollection->Laravel\\Cashier\\Order\\{closure}()`
`#3 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()`
`#4 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(254): Illuminate\\Support\\Collection->map()`
`#5 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(285): Illuminate\\Database\\Eloquent\\Collection->map()`
`#6 /www.mysite.com/vendor/laravel/cashier-mollie/src/Order/OrderItemCollection.php(119): Illuminate\\Support\\Collection->flatMap()`
`#7 /www.mysite.com/vendor/laravel/cashier-mollie/src/Order/Order.php(66): Laravel\\Cashier\\Order\\OrderItemCollection->preprocess()`
`#8 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Laravel\\Cashier\\Order\\Order::Laravel\\Cashier\\Order\\{closure}()`
`#9 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(349): Illuminate\\Database\\Connection->transaction()`
`#10 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\DatabaseManager->__call()`
`#11 /www.mysite.com/vendor/laravel/cashier-mollie/src/Order/Order.php(104): Illuminate\\Support\\Facades\\Facade::__callStatic()`
`#12 /www.mysite.com/vendor/laravel/cashier-mollie/src/Cashier.php(67): Laravel\\Cashier\\Order\\Order::createFromItems()`
`#13 [internal function]: Laravel\\Cashier\\Cashier::Laravel\\Cashier\\{closure}()`
`#14 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()`
`#15 /www.mysite.com/vendor/laravel/cashier-mollie/src/Cashier.php(68): Illuminate\\Support\\Collection->map()`
`#16 /www.mysite.com/vendor/laravel/cashier-mollie/src/Console/Commands/CashierRun.php(31): Laravel\\Cashier\\Cashier::run()`
`#17 [internal function]: Laravel\\Cashier\\Console\\Commands\\CashierRun->handle()`
`#18 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()`
`#19 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()`
`#20 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()`
`#21 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()`
`#22 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()`
`#23 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(201): Illuminate\\Container\\Container->call()`
`#24 /www.mysite.com/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()`
`#25 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(188): Symfony\\Component\\Console\\Command\\Command->run()`
`#26 /www.mysite.com/vendor/symfony/console/Application.php(1012): Illuminate\\Console\\Command->run()`
`#27 /www.mysite.com/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand()`
`#28 /www.mysite.com/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()`
`#29 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()`
`#30 /www.mysite.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()`
`#31 /www.mysite.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()`
`#32 {main}`

Thank you for your time!

Sincerely,

zqstack

**Comment by zqstack** [comment]
Could it be because I changed the name of my plan and I still have references to the old (non-existing) plan name in my database?

**Comment by sandervanhooft** [comment]
Yes that would cause this issue. Updating it in the database should fix this
