### ISSUE TITLE
Extra description lines field doesn't work on shared hosting databases.

### ISSUE THREAD

**Issue by MSnoeren** [laravel/cashier-mollie#16]
The `description_extra_lines` field on the `order_items` table is a JSON-field. I'm in favor of using native types, but unfortunately this field is not yet supported on my shared hosting. I know that's not the best environment to serve a Laravel application from, but I also know I won't be the first to do so ;)

Anyway, this can be fixed by changing the field into a `text` field as Laravel will cast it to a string format. This way all shared-hosting environments will be supported too.

**Comment by MSnoeren** [comment]
#17 I've also created a pull request for this issue.

**Comment by sandervanhooft** [comment]
Agreed. Thanks @MSnoeren !

**Comment by sandervanhooft** [comment]
Merged it!
