### ISSUE TITLE
Pdf OrderInvoiceAvailable duplicates orders?

### ISSUE THREAD

**Issue by Pieterc2** [laravel/cashier-mollie#162]
So i've been working on getting customers to download invoices. When i acces $customers->orders->invoices(); It returns the invoice in an empty {}. So i just want to get the id from this but the pdf has to be download first to server storage i dont really know what to do so some advise would be great. I add the OrderInvoiceAvailable event with a listener that handles downloading the invoice from that order. It gets weird from here. As soon as i place the order the events dont get triggerd anymore but the order still goes through. Then 1 minute later this order duplicates? Very weird.

For example this is my dashboard with the current subscriptions and orders(invoices).
When i placed the first order i didnt receive any mail as it is supposed to do. So the first payment event doesnt get triggerd but it does go through? Then when i wait a couple of minutes this order has duplicated itself what is very weird..

![image](https://user-images.githubusercontent.com/25752853/75541859-e70b0800-5a1e-11ea-83a9-ee4d43e80e3d.png)

My eventserviceprovider
![image](https://user-images.githubusercontent.com/25752853/75541949-2174a500-5a1f-11ea-96d6-75f765a31725.png)

My listener
![image](https://user-images.githubusercontent.com/25752853/75545997-f3479300-5a27-11ea-9d3c-2c61d72d3f30.png)

**Comment by sandervanhooft** [comment]
Hi @Pieterc2,

Have you tried `$order->invoice()` or `$billable->downloadInvoice($orderId)`?

The latter will allow your user to directly download the invoice as pdf.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
