### ISSUE TITLE
Should open payments renew subscriptions in test environment?

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#163]
Dear Developer,

In my orders table I have some orders with `payment_status` `open`, but the subscription is still renewed. Shouldn't it only be renewed when paid? I am still using Mollie Test Environment.

Please find a screenshot attached.
![open payments](https://user-images.githubusercontent.com/60988202/75577682-cb295580-5a62-11ea-8f87-536361dba345.jpg)

zqstack

**Comment by sandervanhooft** [comment]
See our previous discussion: subscription renewal is optimistic. When renewing the billing cycle, a payment is triggered. Depending on the payment method, it can take up to 14 days to clear. That’s why cashier-mollie handles this optimistically.

In case of a failed payment, the subscription is canceled immediately.

**Comment by zqstack** [comment]
Thank you for your reply. Does this mean that I have to wait 14 days in test environment to see whether the subscription payment has succeeded or failed? Or is my webhook not working correctly?

I hope that I'm not asking too many questions. I just want to make sure all payment confugration is set correctly before using it in production.

Sincerely,

zqstack

**Comment by sandervanhooft** [comment]
No problem.

In testmode, mandated payments are not getting to “paid” automatically. You can fetch the payment using `mollie()->payments()->get(“tr_xxxxx”);`. It will contain a link to manually set the status using your browser.
