### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by CodeAndWeb** [laravel/cashier-mollie#167]
First of all: Great work! I started to add the module to my current project and it really seems to do all the stuff I need!

I currently wonder how I could set up easy testing of my own modules (e.g. list of invoices, current plan status, enabled features,...)

What I am looking for is an easy way to create a paying user with a specific plan or configuration without contacting Mollie's API for each request.

**Comment by sandervanhooft** [comment]
Hi @CodeAndWeb, thanks!

You may find your answer here: https://github.com/laravel/cashier-mollie/issues/152 .
