### ISSUE TITLE
CashierRun command throws exception

### ISSUE THREAD

**Issue by tijsbakker** [laravel/cashier-mollie#170]
`ErrorException 

  Object of class Illuminate\Support\Collection could not be converted to int

  at vendor/laravel/framework/src/Illuminate/Console/Command.php:134
    130|      * @return int
    131|      */
    132|     protected function execute(InputInterface $input, OutputInterface $output)
    133|     {
  > 134|         return (int) $this->laravel->call([$this, 'handle']);
    135|     }
    136| 
    137|     /**
    138|      * Resolve the console command instance for the given command.

      +8 vendor frames 
  9   artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
`

**Comment by sandervanhooft** [comment]
Hi @tijsbakker, What Laravel version are you at?

**Comment by tijsbakker** [comment]
hi Sander, Laravel 7 … the exception disappears when I return the $orders->count() in the CashierRun Command.

**Comment by sandervanhooft** [comment]
Released a fix. Thanks for reporting
