### ISSUE TITLE
Payment Method of subscription

### ISSUE THREAD

**Issue by tobischulz** [laravel/cashier-mollie#175]
Is there any way to show the customer his currently used payment method on his active subscription? 

If not, do i have to implement a "payment method" page on checkout to save the selected payment method for this customer to show it on his subscription overview?

Thanks

**Comment by sandervanhooft** [comment]
Hi,

You can use: `$user->mollieMandate()->method;`.

It's stored on the billable/user level, not on subscription level.

**Comment by tobischulz** [comment]
Thank you 😊

**Comment by sandervanhooft** [comment]
No problem, enjoy!
