### ISSUE TITLE
Cannot read session on taxPercentage

### ISSUE THREAD

**Issue by SamAriafar** [laravel/cashier-mollie#176]
To be able to set VAT percentage per each customer, depend on what country they are from, I needed to manipulate taxPercentage on my billable model, but the issue is that after the payment is made, this function is not able to read sessions, however before that everything looks working just fine, because the price includes the additional VAT.

**Comment by SamAriafar** [comment]
I've resolved my own issue by putting a check on session existence on callback and it worked just fine.

**Comment by sandervanhooft** [comment]
Thanks for following up, glad to hear it worked out!
