### ISSUE TITLE
How can i add an addOn to the firstpayment

### ISSUE THREAD

**Issue by nicobleiler** [laravel/cashier-mollie#177]
I tried using a preprocessor but they do not seem to trigger on firstpayment, is there an easy solution without customizing too much of cashier?

**Comment by sandervanhooft** [comment]
Hi,

That's correct, firing the preprocessor on the first payment is still on the roadmap.

You could try using the FirstPaymentBuilder manually. Take a look [here](https://github.com/laravel/cashier-mollie/tree/develop/tests/FirstPayment) for some examples on how this works.

Closing this for now, let me know if it should be reopened.

**Comment by marnickmenting** [comment]
> That's correct, firing the preprocessor on the first payment is still on the roadmap.

@sandervanhooft Will that be possible in v2?
