### ISSUE TITLE
Works with SEPA?

### ISSUE THREAD

**Issue by p0nt** [laravel/cashier-mollie#178]
Not an issue, but a question.

I am not able to find this information on this project, neither in already closed issues on here.

Does this subscription module work with all mollie's subscription possibilities? Also SEPA?

**Comment by sandervanhooft** [comment]
Hi @p0nt,

Yes! In fact SEPA support was the nr 1 reason I developed this package.

Note: Mollie references these payment methods as “direct debit”.

**Comment by p0nt** [comment]
That’s great, thanks Sander for the quick response!

**Comment by sandervanhooft** [comment]
No problem, enjoy!

**Comment by tobischulz** [comment]
Hey,

is #164 still a thing? So on first payment mollie does not accept payment method "directdebit" on my first test. So do i have to follow the steps on the issue 164?

Thanks

**Comment by sandervanhooft** [comment]
No you should be good to go.

**Comment by sandervanhooft** [comment]
See [here](https://github.com/laravel/cashier-mollie/issues/164#issuecomment-598798227)
