### ISSUE TITLE
README is written by irregular markdown. 

### ISSUE THREAD

**Issue by HiroKws** [laravel/cashier-mollie#181]
I know markdown don't have perfect convention. README display in GitHub, however it make trouble when convert HTML or something.

I think it came from nu-escape dot in ordered list items. Simply escape like `1\.`, `2\.`... , and everyone happy. documentaion.md of Laravel official document link to your README. Not native English readers like me, need to translate mother language. Please use common markdown.

**Comment by sandervanhooft** [comment]
I'm not an expert on this, sorry. Feel free to submit a PR 😀
