### ISSUE TITLE
The payment method selected does not accept recurring payments

### ISSUE THREAD

**Issue by leonhh** [laravel/cashier-mollie#185]
I'm trying to create a subscription with ideal. With the test key everything worked as expected. But with a production key we are getting errors.

In the cashier.php config there is this:
```
        /**
         * A comma-separated list of allowed Mollie payment methods for the first payment. Make sure the methods are
         * enabled in the Mollie dashboard. Set to NULL to let Mollie handle this for you. Can be overridden per plan.
         * @example 'ideal,creditcard'
         */
        'method' => 'ideal',

```
When I set it to ideal I get the error message  `The payment method selected does not accept recurring payments`. When I set it to null it only gives me the option to pay with credit card. Meanwhile ideal is also enabled in the Mollie dashboard.

**Comment by sandervanhooft** [comment]
Is this with a first payment (through checkout) or a subsequent payment?

**Comment by leonhh** [comment]
This is with a first payment, i've just been reading through the Mollie help page.

Is it true that SEPA-incasso should also be enabled beside ideal in the Mollie dashboard for the ideal subscriptions to work? In that case, enabling SEPA-incasso will probably fix my problem.

**Comment by sandervanhooft** [comment]
That’s what would make most sense to me right now.

**Comment by leonhh** [comment]
Alright, we've requested SEPA-incasso. Might take 2 days for Mollie to enable it, will get back to you when it still doesn't work.

**Comment by sandervanhooft** [comment]
Thanks! Also happy to know if it _does_ work, so I can help out others with the same issue.

**Comment by leonhh** [comment]
@sandervanhooft just wanted to get back to you on this issue. It seems like I was right, once SEPA Direct Debit was enabled it worked like a charm with ideal. It might also be good idea to mention in the docs that it is necessary to enable SEPA Direct Debit in order to use ideal, bancontact etc.

https://help.mollie.com/hc/en-us/articles/115000967505-How-do-I-apply-for-SEPA-Direct-Debit-via-Mollie-

**Comment by miguelci** [comment]
Completely agree with the comment above, specially because in test mode all works fine.
Only when trying to go live we understand that we still need 2+ more days to get the SEPA Direct Debit.
