### ISSUE TITLE
Changing the invoice pricing format

### ISSUE THREAD

**Issue by pascallieverse** [laravel/cashier-mollie#186]
Currently the invoice shows the price of subscriptions like "209,00 €" using the Cashier::formatAmount. Is there a way to change the format to display it like "€ 209,00"?

**Comment by sandervanhooft** [comment]
Hi @pascallieverse ,

You can set your own formatting callback using `formatCurrencyUsing`.

https://github.com/laravel/cashier-mollie/blob/5f5a8e326595659b6cc47f99c618fba1621a2587/src/Cashier.php#L169
