### ISSUE TITLE
Subscription Swap Error

### ISSUE THREAD

**Issue by nicobleiler** [laravel/cashier-mollie#188]
When i sawp the subscription
`$response = $subscription->swap($plan);`
i get the error:
`Error executing API call (422: Unprocessable Entity): The amount is higher than the maximum. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors`
But i have no problems if i book any of my plans initially, only when "upgrading" by swaping the plan.

**Comment by sandervanhooft** [comment]
This means the plan you're swapping to probably has an amount that's not authorised on your account for this payment method.

It can also happen if another OrderItem is due for processing for this billable model, adding to the amount for the total Order amount.

**Comment by sandervanhooft** [comment]
Closing this for now, let me now if it should be reopened.
