### ISSUE TITLE
Add a migration file for mollie fields

### ISSUE THREAD

**Issue by rabol** [laravel/cashier-mollie#196]
Suggestion:

Part of the installation of this package is to run php artisan cashier:install
It publish some migration files and views.

It would be nice to also have a migration file for adding the fields to the user table - sure It's easy to make your self, but a pre-made would make the whole thing easier :)

**Comment by sandervanhooft** [comment]
Hi!

Thanks for the suggestion, I like to streamline as well.

But the issue with this is that many people are not using the user model/table as the billable model.
