### ISSUE TITLE
webhook_url is not used

### ISSUE THREAD

**Issue by rabol** [laravel/cashier-mollie#197]
In my /config/cashier.php I have changed the webhook_url

e.g.

'webhook_url' => 'https://webhook.site/ae8691c6-4887-4c19-ac2b-a176dfc5e769',

I then did a 
php artisan clear
php artisan config:clear

however, Mollie still throws this error:
Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/guides/handling-errors

Steps to reproduce:
New Laravel project
include the package
get the API key
Use the Controller code from the read.me

**Comment by tormjens** [comment]
@rabol How did you solve it?

**Comment by rabol** [comment]
You have to use an external service like ngrok

It's a little strange that the Mollie service don't have an easier way to test, but that's how it is.

Stripe, paypal etc. does not have this... but that's life

**Comment by sandervanhooft** [comment]
It's the same with Stripe actually, with the difference that they are providing their own forwarder/tunneling solution.

https://stripe.com/docs/webhooks/test
