### ISSUE TITLE
Laravel\Cashier\Exceptions\InvalidMandateException

### ISSUE THREAD

**Issue by nicobleiler** [laravel/cashier-mollie#206]
I get this error on my subscription. I checked the customer in mollie and he still has this exact mandate.
The mandate is also still associated with my laravel user.

Thanks for any help

**Comment by sandervanhooft** [comment]
Have you verified the mandate is still valid?

**Comment by nicobleiler** [comment]
It works sometimes and sometimes not. I set the subscription to a 15 minute cycle, i do not see a pattern why it works only some times

**Comment by nicobleiler** [comment]
I think I had an old Webhook that was causing this

**Comment by sandervanhooft** [comment]
Thanks for clearing that up!
