### ISSUE TITLE
Payment failed, Subscription cancelled

### ISSUE THREAD

**Issue by kyle51north** [laravel/cashier-mollie#211]
What would be the proper way to handle the following use case?

- User passes mandate payment, subscription starts after trial period.
- First SEPA payment fails, Cashier Mollie cancels the subscription
- Customer has sorted out issues with payments on their bank account, so it should not fail anymore. We want retry the payment and resume the subscription.
- ???

Do you just create a new subscription? I could not get a clear answer from the documentation, so I decided to open up an issue.

Great work on this package!

**Comment by sandervanhooft** [comment]
Thanks!

If the subscription is within its grace period, you can use the resume method. Otherwise it’s better to start a new subscription with the same settings.

Hope that clears it up, let me know if you need more information.

**Comment by kyle51north** [comment]
Thanks for the quick response. Surely clears it up!

I think some general information about failed payments and the recommended way to handle them should be in the documentation.

Let me know what you think, I'm willing to create a PR if you agree.

**Comment by sandervanhooft** [comment]
Thanks for clearing that up. I understand your use case. I think a PR on the docs would be best for now.

If you can think of a way to fix this with code, feel free to open an issue ticket or PR with a suggestion.
