### ISSUE TITLE
Multiple subscriptions possible

### ISSUE THREAD

**Issue by ufeg02** [laravel/cashier-mollie#213]
Is it possible with this package to add more than one subscription to a user? We are offering multiple hostingpackages to our customers. One customer can order more than one package and can also order different priced packages. Is there a possibility to achieve this with this package?

**Comment by sandervanhooft** [comment]
Yes it is, but the billing cycles don’t necessarily match up. So if you start multiple subscriptions on different start dates, you may get multiple invoices spread over the month.

**Comment by blankflo** [comment]
Hi , 
I have a question , if the customer is subscribed to multiple subscriptions , the cancel() and swap() method , how they work ?
Can we use them with the subscription id ?
