### ISSUE TITLE
Issue with storing subscription to the subscriptions table in the database 

### ISSUE THREAD

**Issue by yadavsaurabh7** [laravel/cashier-mollie#214]
hi @sandervanhooft 
I was trying to create a subscription but for some reason, it is not automatically inserting subscription in my subscription table ,

 $result = $user->newSubscription($name, 'premium')->create();

            if(is_a($result, RedirectToCheckoutResponse::class)) {
                return $result; // Redirect to Mollie checkout
            }

            Payment::create([
                'user_id'         => auth()->id(),
                'plan_id'         => $plan->id,
                'paid_amount'     => $price,
                'original_amount' => $plan->price,
               // 'discount_id'     => optional($discount)->id,
            ]);

**Comment by sandervanhooft** [comment]
A `RedirectToCheckoutResponse` is returned when the customer has no valid payment mandate yet. In that case the customer is sent through the Mollie checkout and no subscription will be stored in the subscriptions table yet. It will happen once the customer has went through Mollie's checkout and created the mandate, and your webhook gets called. The call to the webhook triggers creating the subscription record.

**Comment by yadavsaurabh7** [comment]
How can I forget the webhooks? 
Got it now it's fixed.
Thanks sander

**Comment by sandervanhooft** [comment]
No worries, it happens to the best of us. Enjoy!
