### ISSUE TITLE
Bug in Subscription::scheduleNewOrderItemAt() ?

### ISSUE THREAD

**Issue by asamMarkus** [laravel/cashier-mollie#217]
When working on a project with the option of swapping plans, I came up with the situation that when swapping a plan by the end of the next cycle (via Subscription::swapNextCycle()) the newly created OrderItem in the database had the description of the old plan instead of the new one.

Searching the code brought me to the following in Subscription::scheduleNewOrderItemAt():
Shouldn'l line 421 rather be
`'description' => $plan->description(),`

![image](https://user-images.githubusercontent.com/66405604/83721363-345cce00-a63b-11ea-9511-f70bcd3edc47.png)

**Comment by sandervanhooft** [comment]
I think you're right!

Could you submit a PR, and check the description in the test?

It's somewhere around [this line](https://github.com/laravel/cashier-mollie/blob/c3cb8104463f4f772a69d4a92b62859924ebdb14/tests/SwapSubscriptionPlanTest.php#L133).

I noticed it's not covered right now.

**Comment by asamMarkus** [comment]
I submitted a PR including test.
Though I coudn't get the tests running. Please countercheck,

**Comment by sandervanhooft** [comment]
Checked it, all good @asamMarkus . Big thanks!

**Comment by sandervanhooft** [comment]
Just released in `v1.13.1`

**Comment by asamMarkus** [comment]
Perfect, thanks for your quick reaction @sandervanhooft
