### ISSUE TITLE
Mollie API Call Unprocessable Entity leads into unprocessed order

### ISSUE THREAD

**Issue by tobischulz** [laravel/cashier-mollie#219]
We got an error from the mollie api:

> The amount is higher than the maximum. Field: amount

We have increased the limit for **direct debit** so that this order can handled by mollie. 

## The Problem

On `php artisan cashier:run` this order_item will not handled cause an order already exist with a temporary _mollie_payment_id_ (temp_4be7058b-xyz...).

How do i retry to create the same order? 

Should i simply delete the temporary order for this order_item, so cashier:run can create a new one?

Thanks

**Comment by sandervanhooft** [comment]
Hi @tobischulz ,

This is about a mandated payment right? So no need for the customer to go through Mollie's checkout

**Comment by tobischulz** [comment]
Hi @sandervanhooft,

this is a direct debit payment with a manually created mandat. So the user has entered his direct debit data, i have created the mandat through the mollie api.  As described in issue #164 .

So the mandat is correct but mollie has not allowed the amount of the order_item. But the order was created without any mollie_payment_status.

php artisan cashier:run does not see this "open" order_item to retry the order through the mollie api.

**Comment by sandervanhooft** [comment]
Ok.

I'm assuming it's used for a subscription and you're not using custom metrics / preprocessing.

- On the `Subscription`, you'll have to reset the `cycle_started_at` and `cycle_ends_at` to the previous cycle. (Once you create the new `Order`, this will be updated to the current cycle - the cycle being paid for with the new `Order`)
- Remove the `Order`
- Clear the `order_id` on the `OrderItem`
- `cashier:run`

**Comment by tobischulz** [comment]
This has worked. Thank you. But i have to delete the previously generated order_item for the next cycle, because that was twice after the new cashier:run. 

But now everything looks good. Thank you!

**Comment by sandervanhooft** [comment]
No problem, glad it worked out. Enjoy!
