### ISSUE TITLE
FirstPaymentPaid Event protected property $payment

### ISSUE THREAD

**Issue by eroelofsen** [laravel/cashier-mollie#22]
I'm implementing the FirstPaymentPaid listener to only create an account when the first payment was successful. 

In my EventServiceProvider.php I've add the listener.
```    
protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        'Laravel\Cashier\Events\FirstPaymentPaid' => [
            'App\Listeners\CreateAccountAfterPayment'
        ]
    ];
```

In my CreateAccountAfterPayment listener I try to access the payment details, but since the payment property is protected I cannot access the details.
```
namespace App\Listeners;

use Laravel\Cashier\Events\FirstPaymentPaid;

class CreateAccountAfterPayment
{
    public function handle(FirstPaymentPaid $event)
    {
        $event->payment; // <-- Cannot access payment details
    }
```

Am I doing something wrong here or should they payment property be public?

**Comment by sandervanhooft** [comment]
@eroelofsen It's not you - you're absolutely right!

Can you submit a PR?

**Comment by robindirksen1** [comment]
@sandervanhooft what do you prefer, a `getPayment` method or making the attribute public?

**Comment by sandervanhooft** [comment]
`public` in this case. Mirrors the other Cashier Events.

**Comment by eroelofsen** [comment]
> @eroelofsen It's not you - you're absolutely right!
> 
> Can you submit a PR?

PR has been created:
https://github.com/laravel/cashier-mollie/pull/23

**Comment by sandervanhooft** [comment]
Merged. Thanks @eroelofsen !
