### ISSUE TITLE
Does a subscription renew automatically when paid with iDEAL

### ISSUE THREAD

**Issue by 1070rik** [laravel/cashier-mollie#223]
I made a subscription and it made me pay with iDEAL.
I have a mandate and when I check the mandate it says "directdebit" as the type.
Does this mean that Mollie will send me a webhook every month when the cycle ends to inform the application is still active or am I missing something? In the Mollie dashboard I can't see any reference to it being recurring.

**Comment by sandervanhooft** [comment]
Cashier will trigger a directdebit payment on the start of the next cycle (when executing `cashier:run`). It uses the mandate for this.
