### ISSUE TITLE
Rounding bug with tax calculations

### ISSUE THREAD

**Issue by ric0tjuh24** [laravel/cashier-mollie#224]
Hello,

Currently there is a bug with the first_payment total caused by a rounding mistake. It might be that this is also the case for the subscription payments later on as it might use the same code.

**Steps to reproduce**
- set the taxPercentage to return 21
- set first payment amount to '10.00'
- create a new newSubscription with trialUntil set, so the first_payment code is used.

**Current result**
The total to be payed is 10.01

**Expcted result**
The total to be payed is 10.00

**Cause**
I tracked it down a bit, but it's too integrated/deep down for me to create a quick PR. What's happening is that you first calculate the tax,  and then subtract this tax from the total amount (**FirstPaymentSubscriptionBuilder@create**). However this subtotal is now a rounded number. The rounded number is added to the actions etc, and then the taxPercentage is re-applied to the rounded number. This is incorrect.

$10/1.21 = $8.26446280992
$8.26446280992 + 8.26446280992*0.21 = $10 = correct

BUT

You pass 10/1.21*100 to the subtotal as 827 (instead of 826.4) and then in preparing the payload (**BaseAction@getTax**) you re-apply the 0.21 tax to the subtotal so 827*0.21 = 173.67 (but this is a wrong number, as its taken from an already rounded number) which is then added to the subtotal ( 827 + 173.67  = 1000.67) and divided by 100 and rounded again to $10.01 = incorrect.

**Comment by sandervanhooft** [comment]
Can you help drafting a PR?

**Comment by netbounty** [comment]
Same problem here. It's rounding too much and it's not precisely

**Comment by sandervanhooft** [comment]
Fixed in [release `v1.14.1`](https://github.com/laravel/cashier-mollie/releases/tag/v1.14.1)
