### ISSUE TITLE
Understanding OrderItems

### ISSUE THREAD

**Issue by yoerriwalstra** [laravel/cashier-mollie#225]
Hi,

tl;dr: what's up with order items without `order_id`? All feedback is appreciated, be it an explanation or link to external source/documentation.

I'm having difficulty understanding the `order_items` table entries. A first order (for one subscription) creates 2 entries in the `order_items` table, where only one has an `order_id`. I haven't tested the entries for renewed order items (or orders) thoroughly yet, because I've only just managed to set up the basic "create a subscription" flow, but I believe renewed order items only create one new entry. Why?

Kind regards,

**Comment by sandervanhooft** [comment]
An order item without order id is an unprocessed order item. It is scheduled to be processed at the process_at date.

**Comment by yoerriwalstra** [comment]
Ah, makes total sense. Thanks for the quick reply!
