### ISSUE TITLE
Relationship between subscriptions and orders

### ISSUE THREAD

**Issue by goyne** [laravel/cashier-mollie#226]
It's not really an issue, but I'm struggling with getting all the orders associated with a specific subscription.

At this moment I only manage to get the orders through the `$subscription->owner->orders` relationship, but then I also get the orders of any other subscription from the same owner.

As far as I can see there is no `$subscription->orders` relation available. How do I achieve this? Or do I misinterpret the package?

Regards.

**Comment by sandervanhooft** [comment]
Probably the best way is via the order items. These contain links to the subscription, the order and the owner

**Comment by goyne** [comment]
So each processed single order item relates to a single order?

**Comment by sandervanhooft** [comment]
One order can have multiple items

**Comment by sandervanhooft** [comment]
> So each processed single order item relates to a single order?

Correct!
