### ISSUE TITLE
FirstPaymentFailed event not triggered using EventSubscriber

### ISSUE THREAD

**Issue by jstam89** [laravel/cashier-mollie#227]
I'm  using an Event Subscriber to trigger FirstPayment events. The success handler is triggered on success but the failed handler is not unfortunatly. What's wrong here? When should the FirstPaymentFailed event trigger?

```
<?php

namespace App\Listeners;

use Illuminate\Support\Facades\Log;
use Laravel\Cashier\Events\FirstPaymentPaid;
use Laravel\Cashier\Events\FirstPaymentFailed;

class FirstPaymentSubscriber
{
    /**
     * Handle first payment paid events.
     *
     * @param FirstPaymentPaid $event
     * @return void
     */
    public function handleFirstPaymentSuccess(FirstPaymentPaid $event)
    {
        Log::notice('first payment success');
    }

    /**
     * Handle first payment failed events.
     *
     * @param FirstPaymentFailed $event
     * @return void
     */
    public function handleFirstPaymentFailed(FirstPaymentFailed $event)
    {
        Log::alert('first payment failed');
    }

    /**
     * @param $events
     * @return void
     */
    public function subscribe($events)
    {
        $events->listen(
            FirstPaymentPaid::class,
            'App\Listeners\FirstPaymentSubscriber@handleFirstPaymentSuccess'
        );

        $events->listen(
            FirstPaymentFailed::class,
            'App\Listeners\FirstPaymentSubscriber@handleFirstPaymentFailed'
        );
    }
}
```

**Comment by juancruzmartino** [comment]
The event is triggered by the Cashier\Http\Controllers\FirstPaymentWebhookController. According to mollie, the webhook will be called when the payment fails and cannot be completed with a different method. Check this out: https://docs.mollie.com/payments/status-changes

**Comment by jstam89** [comment]
Thanks for mentioning that, I've read it and I can't recreate the problem with Mollie. I've tried all the options the test payment screen gives me but in no case I can trigger the FirstPaymentFailed Event.

I was wondering if I did something wrong or if it's an issue the package has and needs to be fixed.

**Comment by sandervanhooft** [comment]
@jstam89 can you verify that `Cashier\Http\Controllers\FirstPaymentWebhookController::handleWebhook()` gets called?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
