### ISSUE TITLE
Plan Swap not working with error Call to a member function handle() on null

### ISSUE THREAD

**Issue by siprasaloni** [laravel/cashier-mollie#228]
when i swap the plan i got error Call to a member function handle() on null (vendor/laravel/cashier-mollie/src/Subscription.php:446)

return $subscription->plan()->orderItemPreprocessors()->handle($item);

but swapNextCycle() working perfectly. 

can you please let me know what is the cause. i am using laravel 6

**Comment by sandervanhooft** [comment]
Seems like the orderItemPreprocessors() call is returning null. Are you perhaps using a customized Plan/Planrepository?

**Comment by siprasaloni** [comment]
hey you are right! i have fixed this. thank you for your time.
