### ISSUE TITLE
Subscription cancelling

### ISSUE THREAD

**Issue by netbounty** [laravel/cashier-mollie#230]
Hey just a question. If a user cancel his subscription via cancelAt(now()): Does Mollie then knows that the user has cancelled his subscription? So that he's not getting charged again? And when I increment the quantity and only allow PayPal as Payment Method, does this automatically increases the amount if i am incrementing the quantity the user has to be charged for? Greets

**Comment by sandervanhooft** [comment]
> If a user cancel his subscription via cancelAt(now()): Does Mollie then knows that the user has cancelled his subscription? So that he's not getting charged again?

The subscription is not managed at Mollie, Mollie is not aware that the payments relate to a subscription. The subscription is managed in this package, which creates payments at Mollie when they are due.

> And when I increment the quantity and only allow PayPal as Payment Method, does this automatically increases the amount if i am incrementing the quantity the user has to be charged for?

Changing the quantity results in the payment amount being updated accordingly, whatever payment method is used.
