### ISSUE TITLE
Re-enable automatic renewal?

### ISSUE THREAD

**Issue by HaikuOezu** [laravel/cashier-mollie#231]
Hi there
First of all congratulations on this nifty little project. I was able to integrate Mollie in my Laravel application in no time!

However, I would like to know if it was possible to implement the following behavior: we want to have the users auto-renew by default, but also cancel auto renewal and re-enable it at any time.
Basically right now I have a subscription and I can just cancel it using the ``cancel()`` method. What I would like to have is the option to have the user say "Actually I would like to auto renew at the end of my subscription", so basically "un-cancel" the subscription without billing them again until the end of the original cycled.

Is this possible or would that require to roll my own subscription logic?
Thanks in advance!

**Comment by sandervanhooft** [comment]
Thanks for the ❤️!

It sounds like you're looking for `$subscription->resume();` which lets you "uncancel" within the grace period. The grace period is essentially the time that was already paid for. After that, the customer should start a completely new subscription.

**Comment by HaikuOezu** [comment]
> Thanks for the ❤️!
> 
> It sounds like you're looking for `$subscription->resume();` which lets you "uncancel" within the grace period. The grace period is essentially the time that was already paid for. After that, the customer should start a completely new subscription.

That is EXACTLY what I was looking for! Thank you!
Looks like I should have tried giving the old thesaurus a try :P

Many thanks!
