### ISSUE TITLE
How to apply tax percentage to discount coupons?

### ISSUE THREAD

**Issue by yoerriwalstra** [laravel/cashier-mollie#232]
It's unclear to me how to add a tax percentage to a Coupon. My goal is to have the discount show up on the invoice as the amount before tax and have the tax percentage over the discount reflected in a reduction of the amount of VAT (below Subtotal)

**Comment by yoerriwalstra** [comment]
To clarify, this is what it looks like now:

![Screenshot 2020-08-06 at 12 21 25](https://user-images.githubusercontent.com/48599583/89521216-65927f80-d7df-11ea-92ab-05cc7fbe8fef.png)

And I would like for it to look like this:

![Screenshot 2020-08-06 at 12 21 25 edit](https://user-images.githubusercontent.com/48599583/89521426-c4f08f80-d7df-11ea-9b91-11f438f1b21d.png)

P.S. sorry for the awful paint skills

**Comment by sandervanhooft** [comment]
Nice paint skills 😆 

Did you try setting `'no_tax' => true` on the coupon's config `context`?

**Comment by yoerriwalstra** [comment]
Ah yes, thanks for your help! You are right that I should set the `no_tax` property on the coupon's `context` array, but instead of `true`, it should actually be `false` if you want to apply the coupon on the price before tax. 

The method `FixedDiscountHandler::taxPercentage` defaults to `true` if you don't provide the `no_tax` key in the coupon's `context`. 

I have to admit that I find the name `no_tax` and its behavior a bit ambiguous and it would also be nice if the behavior would be documented. Apart from that, really loving your package so far, so please don't take this criticism too harshly.

**Comment by sandervanhooft** [comment]
Thanks!
