### ISSUE TITLE
After update the payment method, details still not changed

### ISSUE THREAD

**Issue by mdeprezzo** [laravel/cashier-mollie#233]
Hi @sandervanhooft, about this past discussion:

https://github.com/laravel/cashier-mollie/issues/205

i'll tried the method, in order to update the payment method attached to the subscription, with testmode active. And after update, the credit card number change, but the other details, like card label, card owner and card expiry date doesn't. What am i missing?

**Comment by sandervanhooft** [comment]
What are you doing precisely?

Note that card label/owner/expiry etc are not stored with this package, it's all on the Mollie Mandate resource.

**Comment by mdeprezzo** [comment]
I need to add a feature for the users, to change their payment method, in order to accomplish subscription amount for month. Using that class that you've posted on issue #205 , i can see only the card number changed.

**Comment by sandervanhooft** [comment]
That token is not used by this package.

**Comment by mdeprezzo** [comment]
So, i can't update my payment info? Or add a new card?

**Comment by sandervanhooft** [comment]
You can update the payment method, but you'll need to update the mandate_id on the billable model. The token is something different, it's not being used in this package.

**Comment by mdeprezzo** [comment]
Understood, thanks!

**Comment by sandervanhooft** [comment]
It may be possible to create a first payment with 0 amount using the creditcard token, then obtain the mandate id from there. If you try this, let me know how it goes :)

**Comment by mdeprezzo** [comment]
Sure, i'll try now!

**Comment by blankflo** [comment]
Hi , i am newbie for that package but i enjoy it  , and for my project i need to update payment method .
Can someone help me to do it pls ? 
It will be vey nice , thank you in advance !

**Comment by sandervanhooft** [comment]
@mdeprezzo Did that work? :)
