### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by gegak124** [laravel/cashier-mollie#238]
I translated my file into Arabic, but there is a line that I could not find in the translation files for the control panel and application
Please mention in any line and file find the keys of these words
In the first image the file is before translation, and the option selected is yellow

![123](https://user-images.githubusercontent.com/39296722/91643245-205a1a00-ea3a-11ea-8ac2-fe4435e5fbf9.png)

In the second image, the file after translation and the selected option is red
![1234](https://user-images.githubusercontent.com/39296722/91643246-20f2b080-ea3a-11ea-9350-56eeb7e850b4.png)
I am using the latest version of the 1.6.1 app

**Comment by sandervanhooft** [comment]
This package does not support translations yet, not sure what you're referring to?
