### ISSUE TITLE
What happens if a user reverts the incasso payment?

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#242]
When a user pays via SEPA incasso, and then claims their money back from the incasso, what would happen to their subscription?

I believe I have assigned multiple credit cards and bank accounts to my account (mandate). It seems that multiple cards are being billed and other accounts who use the same card see my invoices as well.

**Comment by sandervanhooft** [comment]
> When a user pays via SEPA incasso, and then claims their money back from the incasso, what would happen to their subscription?

This will be supported in v2.

Only the card for which the mandate_id is stored on your billable model is used to create new payments.

However, payments may take a few days to clear, so there may be overlap. Meaning that a transaction can reach status `paid` on an "old" mandate after a more recent one.
