### ISSUE TITLE
Would it be possible to display the payment method used for mandate?

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#244]
Would it be possible to display the payment method used for mandate? I would like to see which credit card or bank account has been used for the mandate on my website. Is this possible?

I have attached the same credit cards and bank accounts to multiple accounts (mandate). Now when I used swap() to change my plan, it seems that other accounts were activated as well, charging other bank accounts attached. A credit card I previously used, now attached to my colleague is credited, while I used my bank account to start the subscription the last time.

It is difficult to explain. How does it work? Are accounts to be upgraded identified by payment method? I would like to remove the previously used mandates when adding a new one.

Edit: It seems that somehow subscriptions randomly start at time when I wasn't online, even when I canceled the subscription. Why does this happen?

PS: I'm using 5 minutes intervals for my plans for testing purposes.

**Comment by sandervanhooft** [comment]
> Would it be possible to display the payment method used for mandate? I would like to see which credit card or bank account has been used for the mandate on my website. Is this possible?

You can get the payment method from Mollie's mandate, which can be obtained by:

`$mandate = $billable->asMollieCustomer()->getMandate($this->mollie_mandate_id);`

**Comment by zqstack** [comment]
Dear Developer,

Thank you for your answer. I wrote a cron job that revokes all inactive mandates and mandates of subscriptions that have been canceled and out of their grace period, because subscriptions were randomly starting on multiple accounts and accounts would start when using a mandate to the same card as the one upgraded. This helped me to get it working, I guess. My description may be vague, I know!
