### ISSUE TITLE
Multiple Mollie API Key

### ISSUE THREAD

**Issue by andreasbakir** [laravel/cashier-mollie#247]
Hi, I am working on a project where the client has two separate mollie accounts, which results in having to use two api keys, is there a way to set the api key programmatically?

**Comment by sandervanhooft** [comment]
It's not supported by Cashier Mollie, but you may be able to do this by overriding the MollieApiWrapper behavior in the underlying mollie/laravel-mollie. It's loaded in the service container.

**Comment by sandervanhooft** [comment]
Hint: `app("mollie.api");`

Other than that I can offer no support here.
