### ISSUE TITLE
Would it be possible to charge on event?

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#249]
For example, a system uses credits and a user has enabled automatically charging credits when they are below a certain number.

Let's say the system automatically bills a user when credits are below 20, with 20 credits. One credit would cost 2 euros.

So if a user has 23 credits and uses 5 credits, an event is triggered which automatically charges the user 40 euros from their mandate for 20 new credits. The user would then have 48 credits.

Would this be possible?

**Comment by sandervanhooft** [comment]
Cashier Mollie is intended for subscription payments. I have plans for adding one-off payment support, that may cover most of the use case you're describing. But it will never be the goal of this package to support that use case.
