### ISSUE TITLE
Issue in installation process

### ISSUE THREAD

**Issue by JorisDebonnet** [laravel/cashier-mollie#251]
I could not install this package (1.14) using the instructions. 

Running `composer require laravel/cashier-mollie` succesfully installs the required dependencies, but then at the end, the following is automatically run: 
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Mollie\Api\Exceptions\ApiException

  Invalid API key: ''. An API key must start with 'test_' or 'live_' and must be at least 30 characters long.

  at ...\vendor\mollie\mollie-api-php\src\MollieApiClient.php:353
    349|     {
    350|         $apiKey = trim($apiKey);
    351|
    352|         if (!preg_match('/^(live|test)_\w{30,}$/', $apiKey)) {
  > 353|             throw new ApiException("Invalid API key: '{$apiKey}'. An API key must start with 'test_' or 'live_' and must be at least 30 characters long.");
    354|         }
    355|
    356|         $this->apiKey = $apiKey;
    357|         $this->oauthAccess = false;

  1   ...\vendor\mollie\laravel-mollie\src\Wrappers\MollieApiWrapper.php:92
      Mollie\Api\MollieApiClient::setApiKey("")

  2   ...\vendor\mollie\laravel-mollie\src\Wrappers\MollieApiWrapper.php:67
      Mollie\Laravel\Wrappers\MollieApiWrapper::setApiKey()
```

So then I set the API key in .env (and running `php artisan config:cache`), and retried the installation. I still got the same issue. I don't know, maybe this is something due to my own installation, ... in any case, I could finally circumvent the issue by removing `bootstrap/cache/config.php`.

Even if that's an issue on my end, I'd say there's at least a documentation issue, because the mollie key should be set before even trying to install the package. Alternatively, that kind of initiatlisation or check should be delayed until a later time?

**Comment by maksudur-rhmn** [comment]
Did you solve it? I am facing the same issue

**Comment by JorisDebonnet** [comment]
Hi @maksudur-rhmn, you can circumvent it like this: 

1. First set the `MOLLIE_KEY` env variable
2. Then ensure that there is `bootstrap/cache/config.php` file (you can delete it) if it's there
3. Try installing this module again

Another workaround, I figured out later, is to edit the "scripts" section at the bottom of composerjson, and temporarily remove the "post-autoload-dump" there. You'll want to put it back after installing this package though, and once everything is setup and working, run composer dump-autoload to make sure everything is in order.

**Comment by sandervanhooft** [comment]
If you set the key in .env and the problem persists, clearing the config cache should fix it.

**Comment by sandervanhooft** [comment]
Part of the issue may be that `mollie/laravel-mollie` is booted before this Cashier package.

Easiest fix is to mention in Cashier's readme that the key should be set in .env before running `composer require`.

**Comment by sandervanhooft** [comment]
[Fixed it in the readme](https://github.com/laravel/cashier-mollie/commit/38d41af8a6f21a2bf984c370acb137846bb21ff3).

Thanks for reporting @JorisDebonnet

**Comment by maksudur-rhmn** [comment]
> Hi @maksudur-rhmn, you can circumvent it like this:
> 
> 1. First set the `MOLLIE_KEY` env variable
> 2. Then ensure that there is `bootstrap/cache/config.php` file (you can delete it) if it's there
> 3. Try installing this module again
> 
> Another workaround, I figured out later, is to edit the "scripts" section at the bottom of composerjson, and temporarily remove the "post-autoload-dump" there. You'll want to put it back after installing this package though, and once everything is setup and working, run composer dump-autoload to make sure everything is in order.

Thank you :)
