### ISSUE TITLE
Share products in the online store

### ISSUE THREAD

**Issue by gegak124** [laravel/cashier-mollie#252]
I have an online store that has a problem and I want to solve it
The problem is that every vendor adds a product and all the information
But there are a lot of refined products
I want to make a special profile for each product in the Data Base
And the shopkeeper fetch it via the barcode
The image and all information come with the default price, and the store owner can adjust the price anything he wants
What is the code to be added?
Is there a place where I can find all international products (pictures, product data, price, international code, barcode, classification)

**Comment by sandervanhooft** [comment]
This is outside the scope of this package.
