### ISSUE TITLE
Would it be possible to have variable prices for plans?

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#253]
We want to set the price of a plan variable per user, depending on the agreement. Would this be possible?

**Comment by sandervanhooft** [comment]
You may be able to use a preprocessor to do the dynamic calculation. The preprocessors are applied to the collection of order items right before it's processed as an order..

**Comment by zqstack** [comment]
Thank you! The **cashier_plans** file says Preprocessors need to implement **PreprocessesOrderItems**. How do I do that? I didn't see it implemented in other Preprocessors?
