### ISSUE TITLE
Object in Mollie metadata name attr causing webhook to fail

### ISSUE THREAD

**Issue by woutertoday** [laravel/cashier-mollie#256]
Hi guys,

Having a weird issue where Cashier drops my entire Company (uses Billable) Model into the metadata name attribute (found through Mollie's dashboard), which causes webhook calls to fail.

Copied code from the provided example here: https://github.com/laravel/cashier-mollie#creating-subscriptions

Partial Mollie screenshot:
![image](https://user-images.githubusercontent.com/13019569/94691301-6ce28f00-0331-11eb-920e-bd58af2d6a50.png)

Following error in my Laravel Logs:
`"message":"SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at ...`

Which seems obvious since the "name" attribute is about 320 characters long.

Made a migration changing the `name` field of the `subscription` table to `text` instead of `string`, that works. (But results in a really long JSON name, obviously).

**Comment by sandervanhooft** [comment]
Can you paste the exact code you're using here?

**Comment by woutertoday** [comment]
[Model] Company.php


    <?php

    namespace App;

    use Illuminate\Database\Eloquent\Model;
    use Illuminate\Database\Eloquent\SoftDeletes;
    use Laravel\Cashier\Billable;

    class Company extends Model
    {
        use SoftDeletes, Billable;

        protected $dateFormat = 'U';

        protected $casts = [
            'created_at' => 'date:U',
            'updated_at' => 'date:U',
            'deleted_at' => 'date:U',
        ];

        protected $fillable = [
            'name',
            'email',
            // some more
        ];

        public function mollieCustomerFields() {
            return [
                'email' => $this->email,
                'name' => $this->name, // tried changing/removing this, didn't matter
            ];
        }
    }


[Controller] CreateSubscriptionController.php:

    <?php

    namespace App\Http\Controllers;

    use Laravel\Cashier\SubscriptionBuilder\RedirectToCheckoutResponse;
    use Illuminate\Support\Facades\Auth;

    use App\Company;

    class CreateSubscriptionController extends Controller
    {
        /**
         * @param string $plan
         * @return \Illuminate\Http\RedirectResponse
         */
        public function __invoke(string $plan)
        {
            $company = Company::find(1);

            $name = ucfirst($plan) . ' membership';

            if(!$company->subscribed($company, $plan)) {

                $result = $company->newSubscription($company, $plan)->trialDays(7)->create();

                if(is_a($result, RedirectToCheckoutResponse::class)) {
                    return $result; // Redirect to Mollie checkout
                }

                return back()->with('status', 'Welcome to the ' . $plan . ' plan');
            }

            return back()->with('status', 'You are already on the ' . $plan . ' plan');
        }
    }


Still using Laravel 7, by the way.

**Comment by woutertoday** [comment]
I think I might've found something:

On line 102 in Billable.php:

    public function newSubscriptionViaMollieCheckout($subscription, $plan, $firstPaymentOptions = [])
    {
        return new FirstPaymentSubscriptionBuilder($this, $subscription, $plan, $firstPaymentOptions);
    }

Here, a new `FirstPaymentSubscriptionBuilder` contract is called. however, when I look at the `__construct()` method I see this:

    public function __construct(Model $owner, string $name, string $plan, $paymentOptions = [])
    {
        $this->owner = $owner;
        $this->name = $name;

        $this->plan = app(PlanRepository::class)::findOrFail($plan);

        $this->initializeFirstPaymentBuilder($owner, $paymentOptions);

        $this->startSubscription = new StartSubscription($owner, $name, $plan);
    }

So instead of sending the name, we send a Subscription model, which seems to be what I see in Mollie's metadata. Correct me if I'm wrong.

**Comment by sandervanhooft** [comment]
This line in your controller is causing the issue, you're passing the company model in here instead of a string.

`$result = $company->newSubscription($company, $plan)->trialDays(7)->create();`
