### ISSUE TITLE
How to handle partial billing

### ISSUE THREAD

**Issue by jkaan** [laravel/cashier-mollie#259]
Hello! I am aware that this is not supported and might not be at all, however I would like to know your thoughts on how to handle this situation:

Given that for example the subscriptions will be cancelled at any point in time, how would I for do only a partial payment? So usually a subscription runs for an entire month, lets say that I know one month in advance that now this subscription will only run until the 15th of October, how can I make sure that the next order item that will be created, will only be for the period of 1st of October to 15th of October, instead of the entire month?

Any other ideas about this are also much appreciated!

**Comment by sandervanhooft** [comment]
Not sure about your use case, but perhaps running this at the 15th helps:

https://github.com/laravel/cashier-mollie/blob/8973fb3949ad4f59ec2ef0632bad1c148bb22555/src/Subscription.php#L736
