### ISSUE TITLE
Orders table total_due is not updated when mollie_payment_status is "paid"

### ISSUE THREAD

**Issue by eroelofsen** [laravel/cashier-mollie#26]
When a new user subscribes and executes the first payment the total_due column is not updated (I'm using Mollie test api key).

In my case the first payment amount is 1 and the tax is 21%, so total will be 1.21. After the mandate has been given I'd expect the total_due to be 0, but it remain on 1.21.

Ps. The same happens when without using tax.

**Comment by sandervanhooft** [comment]
This is not a bug, it's by design. A payment will always result in a fully paid Order.

The `total_due` is column is named that way because it's the Order's total minus any pre-existing user balance. Hence not `total` but `total_due`.
