### ISSUE TITLE
How to handle pausing of subscriptions

### ISSUE THREAD

**Issue by jkaan** [laravel/cashier-mollie#260]
Hello!

I'm aware of this ticket: https://github.com/laravel/cashier-mollie/issues/235 however I would like to know your opinions on implementing pausing of subscriptions. I can imagine you might not want to implement it in this library, I would like to know though how you would go about implementing this and your thoughts on my current approach.

The current approach which I've implemented is to add a coupon which I called '100-off' which when processed would add an order item which is the entire amount of the order_item that should be billed but then the negative so that the order would always be the amount of zero.

**Comment by sandervanhooft** [comment]
Not sure why you would want that, but it could work.
