### ISSUE TITLE
Subscription creates 2 order items.

### ISSUE THREAD

**Issue by JordyAst** [laravel/cashier-mollie#263]
Forgive me if I have totally misunderstood this. Maybe someone could explain the following situation:

We create subscription, go to mollie, webhook called.

Result:
1 Subscription created
1 Order created
2 Order items created, 1 with order_id NULL and 1 with the Order we created. 

Why do I get 2 order items?

If you need any other info please tell me.

Thanks in advance

**Comment by sandervanhooft** [comment]
This is by design.

One item is processed, one item is scheduled.
