### ISSUE TITLE
get_class() expects parameter 1 to be object, null given on cashier:run

### ISSUE THREAD

**Issue by Dontorpedo** [laravel/cashier-mollie#267]
laravel 7.4
php 7.4

Hi, as the title says, i get a error on running cashier:run, what does it mean?

`get_class() expects parameter 1 to be object, null given {"exception":"[object] (ErrorException(code: 0): get_class() expects parameter 1 to be object, null given at /var/www/mysite/vendor/laravel/cashier-mollie/src/Order/OrderItemCollection.php:56) `

**Comment by Turpoint** [comment]
@Dontorpedo do you remember how you fixed it? I have the same error.
