### ISSUE TITLE
Is it possible to use this plugin together with eCurring? 

### ISSUE THREAD

**Issue by PH-F** [laravel/cashier-mollie#269]
Question, a customer now uses this plugin with mollie and it works fine.
They want to use eCurring instead for recurring payments.

Is it possible to use this plugin together with eCurring?

**Comment by sandervanhooft** [comment]
eCurring is an entirely different product and API, so there's not likely to be any collisions between Cashier and your Ecurring integration. For administration it may make sense to create a separate Mollie profile within the account.

**Comment by PH-F** [comment]
Thank you for the reply.
I see mollie also offers recurring payments now. Can Cashier be used to for this?
