### ISSUE TITLE
questions concerning small payment amounts, invoices and plan updates

### ISSUE THREAD

**Issue by holaa2019** [laravel/cashier-mollie#274]
Hi, I am experimenting with this package and love it so far. Great work!

I discovered required minimum amounts for some payment methods at Mollie. e.g. EPS or Giropay require at least one Euro. 
As I want to allow users to set up their own combination of services and to swap plans and quantity at will, I managed to generate (subsequent) test orders of 0,01 Euro (after a larger first payment) which was no problem in mollie testmode for the particular payment method (credit card). But for other payment methods?

1: Do you know, when using directdebit methods and small amounts, are payments through cashier handled with ease (because they are defaulting to sepa directdebit with a minimum amount of 0,01EUR)? My testing resulted in pending payments.... So I cannot tell. This might also be a question to Mollie?

2: Is there a way to defer the execution of orders in cashier until the payment amount is e.g. larger than 1 EUR? (For reducing paperwork)?

3: Pending payments result in order status "open". OrderInvoiceAvailable is triggered only if the payment is in status "paid". Is there a way in cashier of creating invoices for "open" orders?

4: Is it advisable to block updates of quantity or plans until all payments are fully processed for a subscription? (I manage to generate a lot of credit after downgrading the plan on a subscription with a larger open payment order. If I would have friendly and easy refunding policies, this would be a great way to generate cash for a customer?!).

Thanks

**Comment by sandervanhooft** [comment]
1. Mandated payments in test mode will remain in status pending until you manually modify the status.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/7265703/100483775-5753d080-30fa-11eb-8dc4-df4d27c62ff2.png">

If the order amount is less than Mollie's minimum amount, the amount is deducted from the user's balance in Cashier.

2. No, except for what I describe above.

3. You can manually get the invoice from the Order model. `$order->invoice()`. Note that presenting an invoice before it is paid can make the process a lot harder. I.e. if the payment fails, you now need to manually administer a correcting invoice.

4. Depending on your use cases / business cases some risk management strategies can be advisable. I cannot comment on that.

**Comment by holaa2019** [comment]
Thanks for the quick clarification!
