### ISSUE TITLE
Stripe \ Exception \ InvalidRequestException No such plan: 'basic' using Mollie Cashier

### ISSUE THREAD

**Issue by dimitarmojso** [laravel/cashier-mollie#283]
Hello,

I'm trying to integrate Mollie subscription following the documentation but there is some problem when I try to create a new subscription because also we are using stripe cashier. We are trying to make a test subscription using the default plans in _cashier_plans.php_ but when the user is trying to create new subscriptions it gives us error from Stripe **Stripe \ Exception \ InvalidRequestException No such plan: 'basic'** because the function for making new subscription is the same for both. We changed the configuration in _cashier.php_ but so far there isn't any change.

Any help on this?

**Comment by sandervanhooft** [comment]
You cannot use Cashier Mollie and Cashier Stripe in a single app
