### ISSUE TITLE
Subscription question

### ISSUE THREAD

**Issue by cwwdevelopment** [laravel/cashier-mollie#286]
Hey 

first of all thanks for the great package. This is not a real issue report more a question. The Mollie API does have something like: 

`$customer->createSubscription([
            "amount" => [
                  "currency" => "EUR",
                  "value" => "25.00",
            ],
            "times" => 4,
            "interval" => "3 months",
            "description" => "Quarterly payment",
            "webhookUrl" => "https://webshop.example.org/subscriptions/webhook/",
         ]);`
         
which creates a real subscription at mollie with ids like: sub_123456789 as Abonnement reference. 
So my question is does this package creates a real subscription inside mollie? If not how the recurring payment works exactly? 

best regards

**Comment by sandervanhooft** [comment]
Hi,

Thanks for the ❤️.

Cashier Mollie does not use the Mollie Subscriptions API, but the Payments API. For more details I think [this documentation](https://github.com/laravel/cashier-mollie/blob/develop/README.md#ok-so-how-does-this-all-actually-work) answers your question.

**Comment by sandervanhooft** [comment]
PS. We're not using Mollie's subscription API because it cannot support Cashier's more advanced use cases.

**Comment by cwwdevelopment** [comment]
Thanks for the quick answer i willl take a look.
