### ISSUE TITLE
Welcome status never get's called

### ISSUE THREAD

**Issue by wouterdorgelo** [laravel/cashier-mollie#289]
`return back()->with('status', 'Welcome to the ' . $plan . ' plan');`

never gets called because it's within this statement:

```
if(!$user->subscribed($name, $plan)) {
    //
}
```

Once a payment is done, the user has an active subscription, thus.. He will get status `You are already on the ' . $plan . ' plan'`

**Comment by sandervanhooft** [comment]
It can get called actually.

A user can:

1. be already subscribed to the plan
2. subscribe without an existing mandate, going through Mollie's checkout
3. subscribe with an existing mandate, without going through Mollie's checkout. This is when the statement you're referring can get called.
