### ISSUE TITLE
📢 Claim your seat - Announcing v2 closed alpha

### ISSUE THREAD

**Issue by sandervanhooft** [laravel/cashier-mollie#290]
Hi all,

I'm very happy to announce Cashier Mollie version 2. We're on track to start alpha testing in March. 🤞

Features include **one-off payments**, **refunds** and more 🎉.

An upgrade path will be provided for v1 users. If you run into any problems, we're here to help you out (as always).

_Note that this will be a closed alpha._

So if you'd like to join, please leave a reply below so we can invite you when we're good to go.

\- Sander

**Comment by JoeriAben** [comment]
Count me in!

**Comment by robindirksen1** [comment]
Yes please!

**Comment by jedamzik** [comment]
Would love to participate!

**Comment by lexdewilligen** [comment]
Yes, add me too!

**Comment by wouterdorgelo** [comment]
yes please

**Comment by marvinlinthorst** [comment]
Yes please!

**Comment by bjarn** [comment]
Would love to join :)

**Comment by GertTimmerman** [comment]
Yes, count me in, i was just planning to use Cashier Mollie into a new project ..

**Comment by Beaudinn** [comment]
Would love to join!

**Comment by sandervanhooft** [comment]
Thanks for all the :heart: ! We're getting all fired up here for the alpha release 🔥

**Comment by blankflo** [comment]
Me too !

**Comment by marijnbent** [comment]
Thanks @jelleroorda! I would love to participate Sander 👯‍♀️

**Comment by JordySinke** [comment]
Would love to try it out

**Comment by christophheich** [comment]
Yea, that would be great ❤️

**Comment by salmanhijazi** [comment]
I'm in!

**Comment by Jatarii** [comment]
Would love to test it!

**Comment by jyrkidn** [comment]
I would like to join as well!

**Comment by FutyWidget** [comment]
We love to test it with Futy.

**Comment by Bowero** [comment]
Yes please! 😄

**Comment by stefano-cortese** [comment]
Yes! 😄

**Comment by basiltap** [comment]
Yes please!

**Comment by rortlam** [comment]
Would love to join, too. :-)

**Comment by dseidl** [comment]
Yes please!

**Comment by jaimyborgman** [comment]
Count me in (if still possible)!

**Comment by marnickmenting** [comment]
We just started integrating this library in our SaaS app, but not live yet. Would you recommend to wait for v2 or is the migration not much work?

**Comment by guushuizen** [comment]
Would love to join this!

**Comment by hadjedjvincent** [comment]
I'm in !

**Comment by sandervanhooft** [comment]
Thank you all for all the enthusiasm!

🕙 We're getting really close to the alpha release, polishing some final stuff. Current estimate is that we can launch in 2 to 4 weeks. 🤞

**Comment by sandervanhooft** [comment]
@marnickmenting 

> We just started integrating this library in our SaaS app, but not live yet. Would you recommend to wait for v2 or is the migration not much work?

Great question. It depends on your total project timeline. We have planned the v2 alpha test phase to take 2 to 3 months before it's publicly released as "production ready". An upgrade path will be provided, requiring you to backup your database, migrate and perform some manual changes. Downtime will be anywhere between 0 and 20 minutes.

Personally, if the project allows it and there are other items on the backlog, I'd wait for the v2 alpha.

**Comment by m1nd53t** [comment]
I'm interested as well

**Comment by nusoft** [comment]
Count me in (if it's still possible)!

**Comment by mwllgr** [comment]
Same here! Would love to try the new features.

**Comment by larsjanssen6** [comment]
Please let me in :)

**Comment by bobab12** [comment]
Also interested, please count me in.

**Comment by pepijndik** [comment]
Same here! Would love to try!

**Comment by sandervanhooft** [comment]
Thanks for all the ❤️ !

Our team has had a small development setback due to COVID. I'm really happy everyone came through healthy and enjoys being at work again. The alpha release is pushed back by a few weeks while we're rebuilding the momentum on this package. 

Because of all of your interest we're looking forward to getting this baby shipped.

**Comment by pmochine** [comment]
Would love to try it as well!

**Comment by basiltap** [comment]
@sandervanhooft Any updates about cashier-mollie v2?
You announcied an alpha testing in march, and any code updates in the last two monts.
Is the project still alive?

**Comment by sandervanhooft** [comment]
@basiltap yes. https://github.com/laravel/cashier-mollie/issues/290#issuecomment-824149217

**Comment by vjanssens** [comment]
@sandervanhooft would it be worthwile to wait for v2? I implemented v1 this morning and wonder if I should continue work on it or wait for v2 to be released to the public. How much work will it be to upgrade from v1 to v2?

**Comment by MuhammadSulman** [comment]
When it will be released? I think it was announced in Jan, now it's been more then 5 months, and still pending. please tell me the time frame so that I will not go for both packages for both purposes like subscription and one-time payment.

Thanks.

**Comment by sandervanhooft** [comment]
@MuhammadSulman The alpha code is finished. I'm aiming for next week, only waiting on a green light from Mollie.

**Comment by MuhammadSulman** [comment]
@sandervanhooft Thanks for your reply, I'll wait.,

**Comment by Jaspur** [comment]
@sandervanhooft Any idea if it'll be released today, Friday or somewhere in between?

**Comment by sandervanhooft** [comment]
We're running some final tests and are waiting for Mollie's definite approval.

I don't see any more problems on our way, so strap in for launch this Monday 🚀 .

**Comment by sandervanhooft** [comment]
All on track for launch today 🤞

**Comment by sandervanhooft** [comment]
🔥 🚀 🔥 🚀 🔥 

We're ready to launch :)

Thanks everyone for your patience and more importantly - enthusiasm!

You can expect a GitHub invitation in your mailbox for `sandorianHQ/laravel-cashier-mollie` before the end of the day.

If you are unable to access the repo by tomorrow, please leave a message in this issue ticket and tag me (@sandervanhooft).

To keep things manageable, new sign-ups will be frozen and this ticket will be closed.

See you on the other side!

**Comment by sandervanhooft** [comment]
https://twitter.com/SandervHooft/status/1406962488541945856?s=20

**Comment by MrMooky** [comment]
@sandervanhooft Could I be invited as well?

**Comment by sandervanhooft** [comment]
Public launch ETA Oct/Nov 2021 🤞

**Comment by tomhatzer** [comment]
Hey @sandervanhooft could I possibly be invited as well? I do have a project that would be perfect for using the new version. Thank you very much!

**Comment by lkmadushan** [comment]
@sandervanhooft is there any change to get the beta version? we are waiting for the new version to implement some of the features of a new SaaS app?

**Comment by florianliebig** [comment]
Hey @sandervanhooft - I would like to get an invite here

**Comment by sandervanhooft** [comment]
[![image](https://user-images.githubusercontent.com/7265703/142189462-61701d65-0b27-4e01-a752-65d1d139048a.jpeg)](https://twitter.com/sandervhooft/status/1460920815705333764?s=21)

**Comment by pepijndik** [comment]
Very funny that when you launched the mollie API just crashed this morning

**Comment by sandervanhooft** [comment]
We're breaking the internet here 🔨 

🙃
