### ISSUE TITLE
Easiest way to assign subscriptions (without payment)

### ISSUE THREAD

**Issue by iqfx** [laravel/cashier-mollie#293]
Hello, I am working on a project where we are migrating payment systems.
This means we have users that already have a subscription.

To get straight to the question: Is there any way I can assign a subscription and set a due date without having them pay?
I suppose I could only charge them one cent for the first payment, but then anyone who is new signing up would only have to pay 1 cent as well.

Likely there are some things I don't fully understand yet, but that's why I'm here.

Last but not least, thanks for all of the hard work that went into this ❤️

**Comment by sandervanhooft** [comment]
Thanks for the ❤️  @iqfx !

If I understand correctly you are migrating to Mollie from another payment service provider?

Migrating to Cashier Mollie is not impossible, but it will be tricky.

Personally I'd keep the legacy solution in a separate environment, and do all new sign-ups in the new Cashier Mollie based environment. Then gradually move them over, perhaps throw in a free month or so to give them an incentive to go through Mollie's checkout.

**Comment by iqfx** [comment]
Thanks for your fast response!

I guess this is the best solution without getting to messy.
I guess communication is key here hehe.

Anyway thanks for your insight.

**Comment by sandervanhooft** [comment]
No problem! Good luck and enjoy!
