### ISSUE TITLE
[ERROR] InvalideMandateException -> subscription renewed

### ISSUE THREAD

**Issue by blankflo** [laravel/cashier-mollie#295]
Hi ,
I think i found an error, i'am currently using mollie as recurring solution . One of my client has deleted its mandate before the trial expires, and when the payment was processed an order with a mollie temporary id was created but without any status. The worst thing is the subscription has benn  renewed  for 2 months instead of stopping.

Error links ->https://sentry.io/share/issue/9f28f928f30440c19c1a9832a08289cd/
PS: if you need any help with the alpha , it will be pleasure to helps

Thank you for your time . 

F.L

**Comment by blankflo** [comment]
Thanks for the fast answer .
I'am impatient to discover v2!

I will update mollie and test if its working now .
I'll keep you informed.

F.L

**Comment by sandervanhooft** [comment]
Thanks!

Just released the [patch](https://github.com/laravel/cashier-mollie/releases/tag/v1.16.0).

This should prevent this issue in the future. However, you may need to call `$order->handlePaymentFailedDueToInvalidMandate()` manually on the order that went wrong before. According to your logs this order has ID `109`.

**Comment by blankflo** [comment]
I'll do it right now .

Thanks a lot for your works !
