### ISSUE TITLE
Overwriting redirect_url in config in runtime

### ISSUE THREAD

**Issue by jstam89** [laravel/cashier-mollie#308]
My website has 2 flows when it comes to subscriptions, one is for completely new users and one for allready exsisting users.
At this moment when a new user subscribes the user will be redirected to "/registration?payment_success=true".

For allready subscribed users I want to redirect to a different url but as far as I can see that requires to completely overwrite the config file. Is this correct of is there another way to accomplish this?

I currently use:

`$result = $user->newSubscription('monthly', 'pro')->create();`

**Comment by sandervanhooft** [comment]
Good question. One trick I've learned that may help here is to set the `redirectUrl` to a route attached to a `RedirectedFromMollieController` and decide there where to ultimately redirect the customer to. It's also convenient for displaying the right payment status message etc.. In your case you could check the user's history before redirecting to the appropriate page.

**Comment by jstam89** [comment]
Thanks I will try that.
