### ISSUE TITLE
Cannot process payment without valid mandate for order id

### ISSUE THREAD

**Issue by marijnbent** [laravel/cashier-mollie#313]
![image](https://user-images.githubusercontent.com/11903095/117000330-34e56500-ace1-11eb-9e22-979c095c202a.png)

Data in the database:
![image](https://user-images.githubusercontent.com/11903095/117000451-61997c80-ace1-11eb-892b-2e74b4822036.png)

No order on Mollie exists with the generated number (2021-0000-0194).

I didn't manually change any of the mandates. How can I troubleshoot this?

**Comment by sandervanhooft** [comment]
This happens if for some reason the mandate became invalid. Expired creditcard for example.
