### ISSUE TITLE
When I creating a subscription and fetching the plans from DB It takes me to mollie and I can pay but Order and subscription not get created in DB

### ISSUE THREAD

**Issue by yadavsaurabh7** [laravel/cashier-mollie#318]
@sandervanhooft 

I have used the example provided in the documentation for fetching the plans from DB
If I use the cashier_plans config everthing works fine 
Actually, I wanted to have dynamic prices for each customers 
What am I missing

    public function buildCashierPlan(): CashierPlan
    {
        $plan = new CashierPlan($this->name);
         $plan->setAmount(mollie_array_to_money($this->amount))
            ->setInterval($this->interval)
            ->setDescription($this->description)
            ->setFirstPaymentAmount(mollie_array_to_money($this->amount))
            ->setFirstPaymentDescription($this->first_payment_description)
            ->setFirstPaymentRedirectUrl($this->first_payment_redirect_url)
            ->setFirstPaymentWebhookUrl($this->first_payment_webhook_url)
    ->setOrderItemPreprocessors((OrderItemPreprocessorCollection::fromArray([ProcessCoupons::class,PersistOrderItems::class])));
        return $plan;
    }

**Comment by sandervanhooft** [comment]
Can you look up the payment in the Mollie dashboard and check the events on the right? Most importantly: are the webhook calls to your app being processed ok?

A second place to check is in your app logs.

**Comment by yadavsaurabh7** [comment]
I just check when I do it over the cashier config  file then mandate_id gets filled in 
but when I do the plans over DB the mandate_id not get inserted hence no order, no orderItem and no subscription

**Comment by sandervanhooft** [comment]
Sounds like an issue in your custom db plan repository.
