### ISSUE TITLE
PHP8 update confilct

### ISSUE THREAD

**Issue by ehs4nm** [laravel/cashier-mollie#327]
updating to PHP8, now i get an error.

 Problem 1
    - Root composer.json requires laravel/cashier-mollie 1.14.1 -> satisfiable by laravel/cashier-mollie[v1.14.1].
    - laravel/cashier-mollie v1.14.1 requires php ^7.2 -> your php version (8.0.7) does not satisfy that requirement.

composer.json:
 "require": {
        "php": "^7.3|^8.0",
        "akaunting/money": "^1.1",
..
..

**Comment by sandervanhooft** [comment]
Please update cashier mollie to the latest release (or at least 1.15).
