### ISSUE TITLE
Get checkout URL for failed order payments

### ISSUE THREAD

**Issue by Turpoint** [laravel/cashier-mollie#331]
I'm probably overlooking this. When the payment of an order failed, I want the customer to be able to pay it (for instance with a new credit card). How can I retrieve a checkout URL for an unpaid order?

That way, once the customer has paid the order, there will be a new (valid) mandate linked to his account.

**Comment by sandervanhooft** [comment]
There's no simple feature supporting this. Essentially a failed payment means a failed order.

In v2 we're separating payments from orders, so I'll look into adding a `retry()` to the order there.

For now, I recommend using `$billable->validateMandate()` to flush the invalid mandate and create a new subscription.
