### ISSUE TITLE
Question regarding API KEY

### ISSUE THREAD

**Issue by JantineD** [laravel/cashier-mollie#333]
Hi, is there a way to update the API key on the fly? I'm writing something where I have to correspond with different Mollie account at different moments so I would love to update the API key in a controller or something. Can you help me out?

**Comment by sandervanhooft** [comment]
This package doesn't support that use case.

If you feel like hacking it in anyway, take a look at:

- the CashierServiceProvider
- the ServiceProvider and `mollie()` helper shipped with `mollie/laravel-mollie`
- the Mollie specific Action classes in this Cashier package.

From Mollie's perspective it's recommended to use their OAuth features labeled Mollie Connect when interacting with/on behalf of multiple Mollie accounts.

Hope that helps.
