### ISSUE TITLE
See when a subscription is up for renewal

### ISSUE THREAD

**Issue by iqfx** [laravel/cashier-mollie#335]
Hello I just have quick question and that is to see when a subscription ends.

More specifically a timestamp that represents the date when the subscription is up for renewal.

Is it possible to get this information?

**Comment by sandervanhooft** [comment]
I think the `subscription.cycle_ends_at` field could be used for that:

https://github.com/laravel/cashier-mollie/blob/6acdadc69b00bde337c37a10b6e2f1838ac93217/database/migrations/create_subscriptions_table.php.stub#L28
