### ISSUE TITLE
1305 SAVEPOINT trans2 does not exist

### ISSUE THREAD

**Issue by orangesmints** [laravel/cashier-mollie#337]
I am trying to add a listener to FirstPaymentPaid in EventServiceProvider so I can send a welcome email.

`FirstPaymentPaid::class => [
            SendWelcomeEmail::class
        ]`

The payment goes through just fine but I get Webhook failed with status code 500 in Mollie dash. Upon closer inspection of laravel.log I found this error `SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans2 does not exist`

It has something to do with FirstPaymentHandler execute method since the Order does not get written as well. I am on PHP 7.3.18 and MySql 5.7.24 using laragon on Windows. 

Subscription and order items are saved in the DB but not the order. Thanks in advance!

**Comment by sandervanhooft** [comment]
Hi,

This probably has to do with your mysql instance, either the version or configuration not supporting nested Eloquent transactions. It's not a bug in the package.
