### ISSUE TITLE
Charge based on days of the month left

### ISSUE THREAD

**Issue by bartbergmans** [laravel/cashier-mollie#338]
Hello,

I am currently implementing Mollie in my application but I was wondering if there is a way to only charge per remaining days of the month. For example, the subscription price is 10 euros per month. On the 15th of the month you increase the quantity of your subscription. You only should pay 15 euros that month (1 full price and 1 for only the remaining ~15 days). 

I found that you can increase the quantity of the subscription but not a way to implement this. Any tips or advice for me?

**Comment by sandervanhooft** [comment]
Hi,

This package applies prorating automatically so no need to implement this on your own 👊 😃.
