### ISSUE TITLE
Swapping a plan does not return an RedirectResponse

### ISSUE THREAD

**Issue by marijnbent** [laravel/cashier-mollie#34]
When swapping the plan of a user a Subscription (Laravel\Cashier\Subscription) object is returned, not a RedirectResponse, even though new payments showed up in the Mollie Dashboard (status: pending; method: sepa).

Payments generated:
Tier 2 to tier 1: 0,01 cents
Tier 1 back to tier 2: no payment generated
Tier 2 to tier 3: difference between plans

**Comment by sandervanhooft** [comment]
That’s correct behavior

**Comment by marijnbent** [comment]
Could you elaborate? As the payment is generated in Mollie, shouldn't swap() return the link to let the user pay?

**Comment by sandervanhooft** [comment]
The first payment uses the redirect to obtain a mandate. This mandate is used for all subsequent payments.

**Comment by sandervanhooft** [comment]
Also, too small order amounts do not result in a payment, but in balance being subtracted. A BalanceTurnedStale event will be dispatched if there’s no other order item scheduled for the future.

**Comment by sandervanhooft** [comment]
When swapping a subscription plan, there’s already a mandate for the user.

**Comment by marijnbent** [comment]
Check. So the scheduled `cashier:run` would use this mandate to fulfill the payment? Till then the payment will be pending on Mollie's side. 

Using the announcement "https://github.com/laravel/cashier-mollie#updating-customer-payment-mandates" I could force the creation of a new mandate when swapping plans, to simulate a swapViaMollieCheckout (like newSubscriptionViaMollieCheckout).

Thanks for the explanation!

**Comment by sandervanhooft** [comment]
> So the scheduled cashier:run would use this mandate to fulfill the payment? Till then the payment will be pending on Mollie's side.

No. The payment is generated using the mandate. In live mode, methods like SEPA/directdebit may take up to a few days too clear. In test mode, Mollie allows you to update the status of a mandated payment manually. It's a bit cumbersome, but if you fetch the payment there should be a link included which takes you (developer/tester) to the screen to do this.

**Comment by marijnbent** [comment]
I do run into the following situation right now.
1. User select and pays for plan A.
2. User upgrade to plan B
3. Subscription of user is changed, order is created for the the amount - costs of first plan, status  of order/payment is 'open'
4. When running cashier:run, 'Created 0 orders.' is returned. Payment on the Mollie dashboard stays on pending. Am I missing something?

**Comment by sandervanhooft** [comment]
Hopes that explains it :)

**Comment by marijnbent** [comment]
This clears everything up! In case of iDeal, SEPA takes care of the payments after the first payment. Ofcourse 😓! Tested it with a creditcard and it works like expected. 

Sorry for all the messages, but thanks to your helpful responses!

**Comment by sandervanhooft** [comment]
No problem, it's a complex flow to fully grasp, especially with all the ifs and buts because of the big range of payment methods supported . 

Trust me I know :).
