### ISSUE TITLE
Current subscription end date

### ISSUE THREAD

**Issue by GinJus** [laravel/cashier-mollie#340]
Hi,

With $user->subscribed('main', 'premium'); you receive a true or false on a active subscription but how can I get the current subscription data?

What I want to do is give users a reminder 2 weeks before enddate.

Thank you.

**Comment by WhereIsLucas** [comment]
Based on the migrations, I think there's the `cycle_ends_at` attribute on the subscription attribute.

**Comment by GinJus** [comment]
It shows the started_at date when it not has been cancelled. I hoped there was a function or attribute that shows when the next renewal of the subscription is.

For now I use the $user->subscription('main', 'premium')->cycle_started_at attribute to calculate the next renewal date.

**Comment by sandervanhooft** [comment]
From what you're describing, the `cycle_ends_at` suggested by @WhereIsLucas is what you're looking for.

Note that when the first payment is getting processed and the subscription gets initialised, there's a small moment where the `cycle_ends_at` equals the `cycle_started_at` attribute.

Also, the subscription **_final_** end date is kept in the `ends_at` attribute.

**Comment by GinJus** [comment]
Ok! Thanks (bedankt),

I'm developing on a local machine so the webhook can't be reached. That is probably the reason the date stays the same. When I transfer it to the online testing environment the date changes and is correct.

Thank you!

**Comment by sandervanhooft** [comment]
Great!

When developing locally, consider using a tunnelling service (`valet share` or `ngrok`) to utilize the webhooks.
