### ISSUE TITLE
Travis CI failing on PRs due to confidential env variables not being shared outside repo

### ISSUE THREAD

**Issue by sandervanhooft** [laravel/cashier-mollie#37]
Cashier Mollie tests run against Mollie's API.

The credentials for this are stored confidentially in Travis, as to not overload the test account.

The downside of this is that PRs (hosted at the contributor's repo) do not have access to these credentials, and these tests always fail. (See #33 for example).

**Comment by sandervanhooft** [comment]
FYI @vblinden.

**Comment by sandervanhooft** [comment]
@willemstuursma do you have a suggestion here? Just open up the credentials?

**Comment by willemstuursma** [comment]
Skip the tests if in a PR.

**Comment by sandervanhooft** [comment]
:+1: Good one. Will set up a dev branch as the default.
