### ISSUE TITLE
Can this be used with Paypal accounts?

### ISSUE THREAD

**Issue by bkuhl** [laravel/cashier-mollie#46]
I see Mollie has some support for Paypal.  Does this package (when used with mollie) allow the use of Paying subscriptions via Paypal account balances?

**Comment by RobertBoes** [comment]
PayPal should be supported as payment method, on this page https://www.mollie.com/en/developers/packages/laravelcashier PayPal is listed as supported payment methods for cashier-mollie

**Comment by bkuhl** [comment]
There are varying levels of Paypal compatibility.  Specifically I'm referring to Paypal accounts, subscriptions tied directly with Paypal accounts that pulls from their balance or default payment method, not just associated with a specific payment method.  Cashier traditionally supports a specific payment method, not a general account. which is why I'm asking.

**Comment by sandervanhooft** [comment]
Great question @bkuhl .

Mollie does offer support for one-off payments for PayPal currently, and recurring is on the roadmap. Seems a bit delayed, but I think and hope we can expect it before the end of the year. 🤞

**Comment by mazraara** [comment]
@sandervanhooft does it support paypal now for recurring? is the roadmap of mollie available somewhere online to see? I am using this package on a production website for recurring payments and it works great except with Paypal and SEPA. Thanks much!

**Comment by jponsen** [comment]
Amy update on this? Seems like Mollie supports recurring payments using PayPal now, as mentioned here: https://help.mollie.com/hc/en-us/articles/214072169-Is-Recurring-via-PayPal-also-being-supported-
