### ISSUE TITLE
Migration autoloading

### ISSUE THREAD

**Issue by lexdewilligen** [laravel/cashier-mollie#47]
Making use of Laravels [loadMigrationsFrom()](https://laravel.com/docs/5.8/packages#migrations) method would add the option to keep the migrations as they are without having to publish them. I'd like this feature since it would save me 6 migration files in my database folder.

I'll submit a PR to save you some work!

**Comment by sandervanhooft** [comment]
Thanks, but not a fan of this. Rather provide the ability to inspect and modify the package migrations by default.

**Comment by lexdewilligen** [comment]
Well you could still do so right? But also provide the autoload option

**Comment by sandervanhooft** [comment]
It tends to introduce a number of issues honestly, so it's not common practice to use this in Laravel packages. I feel like the `loadMigrationsFrom()` method should be dropped altogether tbh.

**Comment by lexdewilligen** [comment]
Ok, thanks for you reply!

**Comment by sandervanhooft** [comment]
No problem, really appreciate the contribution ❤️

**Comment by lexdewilligen** [comment]
Could you perhaps provide me with some issues that occur when using migrations autoloading? I don't really understand why providing this would give an issue. It's just an extra feature. If I were to write a PR that doesn't change your current workflow, but does implement `loadMigrationsFrom()`, would you accept it?
