### ISSUE TITLE
StartSubscription error undefined index taxPercentage

### ISSUE THREAD

**Issue by GertTimmerman** [laravel/cashier-mollie#6]
I have successfully made a test payment, i get the welcome message so all seems fine. But when i check if have a valid subscription i get false and i see this error in my log:

```
[2019-06-03 13:01:41] local.ERROR: Undefined index: taxPercentage {"exception":"[object] (ErrorException(code: 0): Undefined index: taxPercentage at .../vendor/laravel/cashier-mollie/src/FirstPayment/Actions/StartSubscription.php:75)
[stacktrace]
#0 .../vendor/laravel/cashier-mollie/src/FirstPayment/Actions/StartSubscription.php(75): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Users/gerttimm...', 75, Array)
#1 .../vendor/laravel/cashier-mollie/src/FirstPayment/FirstPaymentHandler.php(84): Laravel\\Cashier\\FirstPayment\\Actions\\StartSubscription::createFromPayload(Array, Object(App\\Company))
#2 [internal function]: Laravel\\Cashier\\FirstPayment\\FirstPaymentHandler->Laravel\\Cashier\\FirstPayment\\{closure}(Object(stdClass), 0)
#3 /
```

It seems he cannot find taxPercentage in the payload, but in my Billable Model (for me it is App\Company) i have a function taxPercentage() and in the Molle app i can see this metadata:

```
{
  "owner": {
    "type": "App\\Company",
    "id": 2
  },
  "actions": [
    {
      "handler": "Laravel\\Cashier\\FirstPayment\\Actions\\StartSubscription",
      "description": "Monthly payment",
      "subtotal": {
        "currency": "EUR",
        "value": "10.00"
      },
      "taxPercentage": 21,
      "plan": "premium",
      "name": "Premium membership",
      "quantity": 1
    }
  ]
}
```

**Comment by sandervanhooft** [comment]
Hi @GertTimmerman ,

Thanks for trying out the package and reporting this issue.

At first glance I'd say there's an issue in the handler `Laravel\Cashier\FirstPayment\Actions\StartSubscription`.

I'll look into this further, feel free to join.

**Comment by sandervanhooft** [comment]
The `array_filter` method is causing the issue, filtering out any pairs with a `0` value.

**Comment by sandervanhooft** [comment]
Also, can you try upgrading to `v0.1.1` (released this afternoon), so we're on the same page?

**Comment by MSnoeren** [comment]
This is still happening on the latest version. I just got it too. I've had this issue for months but simply fixed it by adding the tax method to the billable model. That's also the reason why I forgot to report it...

**Comment by sandervanhooft** [comment]
It doesn’t explain why it’s happening in the case of @gerttimmerman, who has implemented the same method.

I do have prepared a PR fixing the zero tax issue, but I can’t reproduce the one this ticket was opened for yet.

**Comment by sandervanhooft** [comment]
I've released `v0.1.2` just now, fixing the 0 tax percentage issue.

@GertTimmerman can you check if the issue still occurs with a non-zero tax percentage?

**Comment by GertTimmerman** [comment]
@sandervanhooft i was not able to respond yesterday, but i have tested it and is works like it should work, the issue not occurs anymore. Thanks for the fix!

**Comment by sandervanhooft** [comment]
Thanks @GertTimmerman !
