### ISSUE TITLE
BadMethodCallException: Call to undefined method App\User::getInvoiceInformation()

### ISSUE THREAD

**Issue by meesudzu** [laravel/cashier-mollie#62]
Hi, I'm start with laravel-mollie.
But when I try to call $user->invoices();
It response an BadMethodCallException.
![Screenshot from 2019-09-18 11-27-14](https://user-images.githubusercontent.com/17334624/65111749-6bd10f00-da07-11e9-8a61-2d484533da36.png)
I'm just a beginner with laravel-mollie and I cant find where is the support disscussion.

**Comment by robindirksen1** [comment]
Did you add this trait to the user model as mentioned in the installation instructions?

Laravel\Cashier\Billable

**Comment by meesudzu** [comment]
> Did you add this trait to the user model as mentioned in the installation instructions?
> 
> Laravel\Cashier\Billable

Sure, I follow the Setup steps, and It's in step 6.

**Comment by sandervanhooft** [comment]
You seem to have skipped a few steps within step 6.

**Comment by meesudzu** [comment]
Oh, sorry. I forget to Implement Laravel\Cashier\Order\Contracts\ProvidesInvoiceInformation interface.
Mybad.
