### ISSUE TITLE
Apply coupon to existing subscription

### ISSUE THREAD

**Issue by browar777** [laravel/cashier-mollie#63]
Hi, i have question if is possible to apply coupon to existing subscription ?

**Comment by sandervanhooft** [comment]
Good one. Technically it's possible by creating a `RedeemedCoupon` for an existing subscription manually, but it would be better to provide a helper method on the Subscription model.

Keeping this issue open for this.

**Comment by sandervanhooft** [comment]
It's possible to use the following until then:

```php
RedeemedCoupon::record($this->coupon, $subscription)
```

**Comment by sandervanhooft** [comment]
The coupon would then be automatically applied when the next payment is due.

**Comment by sandervanhooft** [comment]
Adding `$billable->redeemCoupon()` now (`develop`), expect a release later today.

**Comment by sandervanhooft** [comment]
Done. Available now!
