### ISSUE TITLE
[HELP] Is there anyway to store Mollie subscription's plans in database instead of hardcode in config/crashier_plan.php ?

### ISSUE THREAD

**Issue by meesudzu** [laravel/cashier-mollie#64]
As the title,
I need to manager Mollie subscription's plan in admin panel. But it's hardcode config in config/crashier_plan.php.
Is there anyway to store it in database?
Thanks for support.

**Comment by sandervanhooft** [comment]
You can implement the PlanRepository contract and bind it into Laravel’s service container.
