### ISSUE TITLE
Implementing multiplan subscriptions

### ISSUE THREAD

**Issue by lexdewilligen** [laravel/cashier-mollie#65]
As explained in issue [#397](https://github.com/laravel/cashier/issues/397) from Laravel Cashier Stripe, multiplan subscription would be a very nice feature. Could you implement this for us or is this already available? Would you accept PR's on this?

> This is useful because this way the customer will see only one debit on their bank account for every billing cycle instead of seeing one for every subscribed plan. Eg. if your customer is subscribed to a main service plus 4 features, they will get 5 debits every month. This is bad for service providers because (a) it is ugly (b) it is more expensive due to the fix fees.

**Comment by sandervanhooft** [comment]
Hi @lexdewilligen,

Yeah this was one of the architecture concerns when I started this project.

You can implement this by scheduling `Cashier::run()` to run monthly (or tinker with the underlying method to match it better to your use case).

All order items that are due at that moment will be processed into one single order (and invoice). Multiple currencies will be split into multiple orders.
