### ISSUE TITLE
Possible bug found: Argument 1 passed to mollie_object_to_money() must be an instance of object, instance of stdClass given, called in vendor/laravel/cashier-mollie/src/MinimumPayment.php on line 21

### ISSUE THREAD

**Issue by jkaan** [laravel/cashier-mollie#67]
While Laravel runs the scheduled job I get the following error. Weird however is that if I run `cashier:run` myself from the CLI, it just works.

When retrieving the minimum payment the object is a stdClass and not an object and that is what is going wrong apparently.

**Comment by jkaan** [comment]
Found that the scheduled job was using PHP 7.1, which was in /usr/bin/php and I was myself using /usr/local/bin/php which was 7.3.

**Comment by burtontanner** [comment]
@jkaan is this an issue with php 7.3? that is the same version that I am using.

**Comment by jkaan** [comment]
@burtontanner I'm not too clear on why actually the error occurs, but I think it is related to the fact that in PHP 7.2 you can use the `object` typehint which doesn't match with stdClass. PHP 7.1 ignores this however PHP 7.3 does enforce it and it fails.

**Comment by SnoxiK** [comment]
nobody found a solution because I'm in the same dead end???


`Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in`
