### ISSUE TITLE
Usage with Mollie Connect

### ISSUE THREAD

**Issue by jkaan** [laravel/cashier-mollie#68]
I'm working on an application which uses Mollie Connect to setup subscriptions using Mollie accounts from third parties.

I would like to leverage this library to for example handle swapping plans on the next cycle and pausing or resuming the current subscription.

I'm trying to find out a way to make this work, I think I have an idea but I was wondering if you have an idea on how to make this work :).

Thanks a lot!

**Comment by runforrestrun** [comment]
> I'm trying to find out a way to make this work, I think I have an idea but I was wondering if you have an idea on how to make this work :).

What is your question exactly?

**Comment by sandervanhooft** [comment]
This package was not designed to be used with Mollie Connect / OAuth(2) / Laravel Socialite. Can't help you there, sorry. 🤷‍♂
