### ISSUE TITLE
How does PlanRepository work to add plans to a migration instead of the config file?

### ISSUE THREAD

**Issue by Jabirr** [laravel/cashier-mollie#69]
Hi,

I have read in another post that if you want to make a migration for your plans that you should use PlanRepository. How does this work?

- Jabir

**Comment by RobertBoes** [comment]
Hey @Jabirr,

It seems like you'd have to bind the contract `Laravel\Cashier\Plan\Contracts\PlanRepository` to your own implementation that implements this contract. 

You can do this in a service provider of your own like this:
```
$this->app->bind(PlanRepository::class, DatabasePlanRepository::class);
```

Your DatabasePlanRepository class would then contain the logic of fetching the items from the database, but you'll have to make sure you're returning objects that implement `Laravel\Cashier\Plan\Contracts\Plan`.

You can make your own eloquent Plan model, have it implement `Laravel\Cashier\Plan\Contracts\Plan`, implement all the required methods, and then a database repository would be something like this:

```
use App\Plan;
use Laravel\Cashier\Plan\Contracts\PlanRepository;

class DatabasePlanRepository implements PlanRepository
{
    /**
     * @param string $name
     * @return null|\Laravel\Cashier\Plan\Contracts\Plan
     */
    public static function find(string $name)
    {
        return Plan::where('name', $name)->first();
    }

    /**
     * @param string $name
     * @return \Laravel\Cashier\Plan\Contracts\Plan
     */
    public static function findOrFail(string $name)
    {
        return Plan::where('name', $name)->firstOrFail();
    }
}
```

**Comment by Jabirr** [comment]
Hey thx for the start.
Im trying to figure out what i need to put in a migration to migrate the right data.
I thought of something like this. 
![image](https://user-images.githubusercontent.com/31471200/65885567-2dd6d200-e39b-11e9-9323-65dd9adbba3f.png)
Do i need to add something in the cashier_plans.php so it can refer to a db too? because when you search for a plan that doesnt exist it will say that the plan doesnt exist. Using your code and then searching for a plan that doesnt exist just gives me a 404 page.  Idk if im just stupid (which probably is) but i dont really seem to understand what i need to do. If you could help me further that would be great.

-Jabir

**Comment by RobertBoes** [comment]
I think you're on the right track. If you're using your own implementation of PlanRepository you don't need to worry about the config in `cashier_plans` (because this isn't used anymore).

The 404 is because, in my example, `DatabasePlanRepository->findOrFail()` uses the default eloquent method (findOrFail), this throws a ModelNotFound exception. I think you'll need to throw a `PlanNotFoundException`. By looking at the ConfigPlanRepository, you can just do something like this:
```php
public static function findOrFail(string $name)
{
    if (($result = Plan::where('name', $name)->first()) != null) {
        return $result;
    } else {
        throw new PlanNotFoundException;
    }
}
```

One thing you're missing, is implementing the Plan contract (`Laravel\Cashier\Plan\Contracts\Plan`) in your own model:
```php
class Plan extends Model implements Laravel\Cashier\Plan\Contracts\Plan
{

}
```
If you're using an IDE you should then see you need to implement those methods. You can look how these methods are implemented in [Plan](https://github.com/laravel/cashier-mollie/blob/develop/src/Plan/Plan.php). After you've implemented these methods it should work the same the config, but then with your own repository (the DB).

**Comment by Jabirr** [comment]
Hi @RobertBoes 

First of all, thx for the quick reply. I kind of figured the implementing out too. I think the only issue is now is that it cant find a currency 
![image](https://user-images.githubusercontent.com/31471200/65887786-cde22a80-e39e-11e9-96f2-0ba6be3f8142.png)

How ever, searching through the code i found out it finds a plans value like this. 
![image](https://user-images.githubusercontent.com/31471200/65887836-e3575480-e39e-11e9-90fe-bfee266b4c76.png)

If I dd my own plan it will return this. 
![image](https://user-images.githubusercontent.com/31471200/65887926-0aae2180-e39f-11e9-81db-8290d2d5c85c.png)

If i dd the plan using the normal plan configuration it will return this.
![image](https://user-images.githubusercontent.com/31471200/65888032-2b767700-e39f-11e9-8da0-bc8a98f52dd9.png)

So i guess the next step would be returning the same values as using the normal configuration.
Do you have any idea how i could achieve this?
Thx a lot for helping out too btw!

- Jabir

**Comment by Jabirr** [comment]
Hey guys, 

I figured it out with help of @RobertBoes ofcourse.

First of all to start using an custom PlanRepository. You have to bind the contract Laravel\Cashier\Plan\Contracts\PlanRepository to your own implementation that implements this contract.

You can do this in a service provider of your own like this:
```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register the application services.
     */
    public function register()
    {
        $this->app->bind(PlanRepository::class, DatabasePlanRepository::class);
    }
}
```
Your DatabasePlanRepository class would then contain the logic of fetching the items from the database, but you'll have to make sure you're returning objects that implement Laravel\Cashier\Plan\Contracts\Plan.

You can make your own eloquent Plan model, have it implement Laravel\Cashier\Plan\Contracts\Plan, implement all the required methods, and then a database repository would be something like this:
```
use App\Plan;
use Laravel\Cashier\Plan\Contracts\PlanRepository;

class DatabasePlanRepository implements PlanRepository
{
    /**
     * @param string $name
     * @return null|\Laravel\Cashier\Plan\Contracts\Plan
     */
    public static function find(string $name)
    {
        return Plan::where('name', $name)->first();
    }

    /**
     * @param string $name
     * @return \Laravel\Cashier\Plan\Contracts\Plan
     */
public static function findOrFail(string $name)
{
    if (($result = Plan::where('name', $name)->first()) != null) {
        return $result;
    } else {
        throw new PlanNotFoundException;
    }
}
}
```

Now make a model for example Plan.php, I will show mine model. You have to import all the Plan functions into the model and change it with the values you save in your db.

```<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Laravel\Cashier\Order\OrderItemPreprocessorCollection;
use Money\Currency;
use Money\Money;
use Laravel\Cashier\Plan\Contracts\Plan as PlanImplements;


class Plan extends Model implements PlanImplements
{
    protected $fillable = [
        'name', 'amount', 'interval', 'description', 'currency','firstPaymentDescription','firstPaymentAmount'
    ];


    public function getCurrency(Currency $currency)
    {
        return $this->attributes['currency'];
    }

    public function getCode()
    {
        return $this->attributes['currency'];


    }

    public function amount()
    {


        $currency = new Currency($this->getCode());
        return new Money($this->attributes['amount'] * 100, $currency);
    }

    /**
     * @param \Money\Money $amount
     * @return \Laravel\Cashier\Plan\Contracts\Plan
     */
    public function setAmount(Money $amount)
    {
        $this->attributes['amount'] = $amount;

        return $this;
    }

    /**
     * @return string
     */
    public function description()
    {
        return $this->attributes['description'];

    }

    /**
     * @return string
     */
    public function interval()
    {
        return $this->attributes['interval'];

    }

    /**
     * @return string
     */
    public function name()
    {
        return $this->attributes['name'];
    }

    /**
     * The amount the customer is charged for a mandate payment.
     *
     * @return \Money\Money
     */
    public function firstPaymentAmount()
    {
        $currency = new Currency($this->getCode());
        return new Money($this->attributes['firstPaymentAmount'] * 100, $currency);
    }

    /**
     * @param \Money\Money $firstPaymentAmount
     * @return Plan
     */
    public function setFirstPaymentAmount(Money $firstPaymentAmount)
    {

    }

    /**
     * @return string
     */
    public function firstPaymentMethod()
    {


    }

    /**
     * @param string $firstPaymentMethod
     * @return Plan
     */
    public function setFirstPaymentMethod(?string $firstPaymentMethod)
    {

    }

    /**
     * The description for the mandate payment order item.
     *
     * @return string
     */
    public function firstPaymentDescription()
    {

        return $this->attributes['firstPaymentDescription'];
    }

    /**
     * @param string $firstPaymentDescription
     * @return Plan
     */
    public function setFirstPaymentDescription(string $firstPaymentDescription)
    {

    }

    /**
     * @return string
     */
    public function firstPaymentRedirectUrl()
    {
        return "http://localhost:8000/redirect";
    }

    /**
     * @param string $redirectUrl
     * @return Plan
     */
    public function setFirstPaymentRedirectUrl(string $redirectUrl)
    {

    }

    /**
     * @return string
     */
    public function firstPaymentWebhookUrl()
    {
        return "webhookurl;

    }

    /**
     * @param string $webhookUrl
     * @return Plan
     */
    public function setFirstPaymentWebhookUrl(string $webhookUrl)
    {
    }

    /**
     * @return \Laravel\Cashier\Order\OrderItemPreprocessorCollection
     */
    public function orderItemPreprocessors()
    {

    }

    /**
     * @param \Laravel\Cashier\Order\OrderItemPreprocessorCollection $preprocessors
     * @return \Laravel\Cashier\Plan\Contracts\Plan
     */
    public function setOrderItemPreprocessors(OrderItemPreprocessorCollection $preprocessors)
    {


        $this->orderItemPreprocessors = $preprocessors;

        return $this;
    }
}
```

Now you can insert your plans into a db.
![image](https://user-images.githubusercontent.com/31471200/65899573-4e5f5600-e3b4-11e9-9823-e41138b5a09f.png)


This was a quick fix but I am 100% sure that this can be made better.
I also want to thanks @RobertBoes for his time and help.
If someone has a beter way of achieving this. Id like to know that too!

**Comment by alexander-rieder** [comment]
@Jabirr could you also post your migration file? :)

**Comment by Jabirr** [comment]
@alexander-rieder ofc,

` public function up()
    {
        Schema::create('plans', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->text('description')->nullable();
            $table->string('interval')->default('monthly');
            $table->double('amount');
            $table->string('currency')->default('EUR');
            $table->text('firstPaymentDescription')->nullable();
            $table->double('firstPaymentAmount')->default(0.01);
            $table->string('firstPaymentCurrency')->default('EUR');
            $table->text('modules');
            $table->softDeletes();
            $table->timestamps();
        });
    }`
