### ISSUE TITLE
The times property of a coupon is not used

### ISSUE THREAD

**Issue by sebastiaands** [laravel/cashier-mollie#76]
In the `cashier_coupons.php` cofig file, you can set the `times` property.
This property doesn't seem to be used. After applying a coupon with a `times` value higher than 1 the `times_left` column in the `redeemed_coupons` table is always 0 (or 1 before processing the order).

**Comment by sandervanhooft** [comment]
Thanks.

Can you check whether 1) this only happens on first payments, and 2) a AppliedCoupon record was created?

**Comment by sebastiaands** [comment]
This happens on both first payments and other payments. And an AppliedCoupon object is created.

**Comment by sandervanhooft** [comment]
Found it, the issue is in the `ConfigCouponRepository`. Preparing a PR.

**Comment by sandervanhooft** [comment]
@sebastiaands , can you give the `develop` branch a spin?

**Comment by sandervanhooft** [comment]
Should fix both of your issues.

**Comment by sebastiaands** [comment]
Hi @sandervanhooft , both issues seem to be fixed.
Thanks!

**Comment by sandervanhooft** [comment]
Released! https://github.com/laravel/cashier-mollie/releases
