### ISSUE TITLE
Target [Laravel\Cashier\Coupon\Contracts\CouponRepository] is not instantiable.

### ISSUE THREAD

**Issue by Jabirr** [laravel/cashier-mollie#81]
Hi

I have made a project where users can subscribe to a plan. Its working as intended on my local server and today I pushed it to my testing server. When ever i want to go to the checkout it will give me this error. 

![image](https://user-images.githubusercontent.com/31471200/66324771-5b38f800-e926-11e9-82f9-a1b528c6c142.png)

Its before i get on the mollie checkout page. And it seems to break at StartSubscription.php at line 62 
![image](https://user-images.githubusercontent.com/31471200/66324857-8ae80000-e926-11e9-9598-10f5e3403238.png)

Im wondering what is wrong since its not giving me this error on my local server.

regards, Jabir

**Comment by RobertBoes** [comment]
Have you created your own implementation of CouponRepository, like you asked for the PlanRepository in #69 ? If so, could you share the code where you're binding the CouponRepository and how your implementation looks like?

**Comment by Jabirr** [comment]
No i did not, in fact im not using coupons in my application at this moment. Thats why i am wondering why its not working. Is there something i have turned on while its asking for a coupon but it cant find one? And thus giving me this error?

**Comment by sandervanhooft** [comment]
First things first: can you check you're using the same versions in both environments?

**Comment by Jabirr** [comment]
Hi @sandervanhooft 

They are both the same version
```        "laravel/cashier-mollie": "^1.0",
```

- Jabir

**Comment by sandervanhooft** [comment]
Can you use `composer show laravel/cashier-mollie` to check the actual version installed?

The `composer.json` file will only show you what versions are _allowed_.

**Comment by sandervanhooft** [comment]
What version specifically?

**Comment by Jabirr** [comment]
V1.1.0 on both local and server.

**Comment by sandervanhooft** [comment]
Can you upgrade to the latest, on both machines?

**Comment by sandervanhooft** [comment]
We're at `v1.2.3` currently

**Comment by Jabirr** [comment]
Updating to the newer versions seemed to fix the problem. Sorry for not realising earlier!

**Comment by sandervanhooft** [comment]
No problem, thanks for the follow-up!

**Comment by Jabirr** [comment]
I know its a question i shouldnt be asking here, but do you have something like a place where we can ask quick questions like discord. Im now wondering why my webhook isnt working on the live server. Even tho its saying on the mollie dashboard what the webhook is. So im wondering where i can help like this? Or is opening a new issue fine too.
