### ISSUE TITLE
Can't upgrade to laravel 6.2

### ISSUE THREAD

**Issue by pascallieverse** [laravel/cashier-mollie#84]
- cashier-mollie: 1.2.3
- Laravel Version: 6.0.3
- PHP Version: 7.2.11

When upgrading Laravel from 6.0.3 to laravel 6.2 cashier gives the following error when running composer update

  `Problem 1
    - Conclusion: remove laravel/cashier-mollie v1.2.3
    - Installation request for laravel/cashier-mollie 1.2.3 -> satisfiable by laravel/cashier-mollie[v1.2.3].
    - Conclusion: don't install laravel/framework v6.2.0
    - laravel/cashier-mollie v1.2.3 requires illuminate/support ~5.8.0|~6.0.0 -> satisfiable by laravel/framework[v6.0.4, 5.8.x-dev], illuminate/sup
port[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29,
 v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - Can only install one of: laravel/framework[6.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, v6.0.4].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.0|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.11|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.12|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.14|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.15|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.17|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.18|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.19|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.2|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.20|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.22|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.24|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.27|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.28|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.29|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.3|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.30|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.31|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.32|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.33|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.34|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.35|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.4|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.8|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v5.8.9|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v6.0.0|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v6.0.1|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v6.0.2|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v6.0.3|don't install laravel/framework 6.x-dev
    - don't install illuminate/support v6.0.4|don't install laravel/framework 6.x-dev
    - Installation request for laravel/framework ^6.2 -> satisfiable by laravel/framework[6.x-dev, v6.2.0].`

**Comment by pascalbaljet** [comment]
This was fixed recently (https://github.com/laravel/cashier-mollie/pull/82) but I think it’s not in 1.2.3 yet.

**Comment by pascallieverse** [comment]
If you see the release notes of 1.2.3 it should be fixed with your commit but its not working: https://github.com/laravel/cashier-mollie/releases/tag/v1.2.3

**Comment by sandervanhooft** [comment]
Yeah something went wrong it seems. Will look into it. Thanks for reporting.

**Comment by sandervanhooft** [comment]
Done. Use `v1.2.4`.

**Comment by pascallieverse** [comment]
Thanks, can confirm 1.2.4 is fixing the problem.

**Comment by sandervanhooft** [comment]
Thanks for confirming. The root cause was that the develop / master branch workflow was messing with my head 🤦‍♂ .
