### ISSUE TITLE
How should I get the order from the OrderItem ?

### ISSUE THREAD

**Issue by larsjanssen6** [laravel/cashier-mollie#91]
Hi,

I'm trying to get the `Order` from an `OrderItem` but I don't see 
a `belongsTo` relation on the `OrderItem`. 

Only `orderable` and `owner`.  Maybe we should add it?

Thanks!

**Comment by sandervanhooft** [comment]
Sure, feel free to send in a PR.

**Comment by larsjanssen6** [comment]
#92

**Comment by sandervanhooft** [comment]
#92 Merged into `develop`. Thanks @larsjanssen6 !
