### ISSUE TITLE
Can't get invoices

### ISSUE THREAD

**Issue by Anthony2511** [laravel/cashier-mollie#94]
Hello,

I'm trying to retrieve the list of invoices. 

```php
public function getInvoicesForUser()
    {
        $user = Auth::user();

        if (count($user->orders) > 0) {
            return response()->json([ 'invoices' => $user->orders->invoices() ], 200);
        }

        return response()->json('No invoices');
    }
```

In my JSON response, I get an empty array. Do you know why ?

My orders table contains some data. 

Can you explain me ?

Thank you !

**Comment by sandervanhooft** [comment]
Hi @Anthony2511,

The `Invoice` is a plain php object. You'll need to build the array you want using the object getters.

Alternatively, I'm open to a PR adding a `toArray()` method. 😄
