### ISSUE TITLE
SubscriptionCreated Event

### ISSUE THREAD

**Issue by pascallieverse** [laravel/cashier-mollie#96]
It would be nice to have a special event for when a subscription is created and paid or a trial is requested so that its possible for example to setup some files when a user subscription is starting.

It should be fired when `newSubscription` is called with an existing mandate or when the redirect is done to Mollie and the payment is paid.  Or when a subscription is created with the trial option it should be fired immediately without payment.

**Comment by sandervanhooft** [comment]
Hi @pascallieverse ,

Agreed.

The implementation doesn't have to be complex though. The event should fire when the Subscription Eloquent model is created, as in the example [here](https://laravel.com/docs/6.x/eloquent#events).

Feel free to submit a PR (don't forget the tests).

**Comment by pascallieverse** [comment]
Thanks,

I will start working on the PR now

**Comment by sandervanhooft** [comment]
Could you add it to the event list in the README as well?

**Comment by sandervanhooft** [comment]
Available now on `v1.4.0`! Thanks again @pascallieverse !
